// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_cards.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createBusinessCard = `-- name: CreateBusinessCard :exec

INSERT INTO
  business_cards (
    id,
    card_number_enc,
    last4,
    label,
    bank,
    holder_name,
    expiry,
    card_limit,
    status,
    created_at,
    updated_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBusinessCardParams struct {
	ID            string         `json:"id"`
	CardNumberEnc string         `json:"cardNumberEnc"`
	Last4         string         `json:"last4"`
	Label         sql.NullString `json:"label"`
	Bank          sql.NullString `json:"bank"`
	HolderName    sql.NullString `json:"holderName"`
	Expiry        sql.NullString `json:"expiry"`
	CardLimit     sql.NullInt64  `json:"cardLimit"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

// ============================================
// business_cards / business_card_assignments queries
// ============================================
func (q *Queries) CreateBusinessCard(ctx context.Context, arg CreateBusinessCardParams) error {
	_, err := q.db.ExecContext(ctx, createBusinessCard,
		arg.ID,
		arg.CardNumberEnc,
		arg.Last4,
		arg.Label,
		arg.Bank,
		arg.HolderName,
		arg.Expiry,
		arg.CardLimit,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createBusinessCardAssignment = `-- name: CreateBusinessCardAssignment :exec
INSERT INTO
  business_card_assignments (card_id, user_id, assigned_by, assigned_at)
VALUES
  (?, ?, ?, ?)
`

type CreateBusinessCardAssignmentParams struct {
	CardID     string    `json:"cardId"`
	UserID     string    `json:"userId"`
	AssignedBy string    `json:"assignedBy"`
	AssignedAt time.Time `json:"assignedAt"`
}

func (q *Queries) CreateBusinessCardAssignment(ctx context.Context, arg CreateBusinessCardAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, createBusinessCardAssignment,
		arg.CardID,
		arg.UserID,
		arg.AssignedBy,
		arg.AssignedAt,
	)
	return err
}

const deleteBusinessCard = `-- name: DeleteBusinessCard :exec
DELETE FROM business_cards
WHERE
  id = ?
`

func (q *Queries) DeleteBusinessCard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBusinessCard, id)
	return err
}

const getActiveBusinessCardAssignment = `-- name: GetActiveBusinessCardAssignment :one
SELECT
  id, card_id, user_id, assigned_by, assigned_at, released_at
FROM
  business_card_assignments
WHERE
  card_id = ?
  AND released_at IS NULL
`

func (q *Queries) GetActiveBusinessCardAssignment(ctx context.Context, cardID string) (BusinessCardAssignment, error) {
	row := q.db.QueryRowContext(ctx, getActiveBusinessCardAssignment, cardID)
	var i BusinessCardAssignment
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getBusinessCardByID = `-- name: GetBusinessCardByID :one
SELECT
  id, card_number_enc, last4, label, bank, holder_name, expiry, card_limit, status, created_at, updated_at
FROM
  business_cards
WHERE
  id = ?
`

func (q *Queries) GetBusinessCardByID(ctx context.Context, id string) (BusinessCard, error) {
	row := q.db.QueryRowContext(ctx, getBusinessCardByID, id)
	var i BusinessCard
	err := row.Scan(
		&i.ID,
		&i.CardNumberEnc,
		&i.Last4,
		&i.Label,
		&i.Bank,
		&i.HolderName,
		&i.Expiry,
		&i.CardLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessCardForUpdate = `-- name: GetBusinessCardForUpdate :one
SELECT
  id
FROM
  business_cards
WHERE
  id = ?
FOR UPDATE
`

func (q *Queries) GetBusinessCardForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getBusinessCardForUpdate, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const listAllBusinessCards = `-- name: ListAllBusinessCards :many
SELECT
  c.id,
  c.last4,
  c.label,
  c.bank,
  c.holder_name,
  c.expiry,
  c.card_limit,
  c.status,
  c.created_at,
  c.updated_at,
  a.user_id AS owner_id,
  a.assigned_at AS assigned_at
FROM
  business_cards c
  LEFT JOIN business_card_assignments a ON a.card_id = c.id
  AND a.released_at IS NULL
ORDER BY
  c.created_at DESC
`

type ListAllBusinessCardsRow struct {
	ID         string         `json:"id"`
	Last4      string         `json:"last4"`
	Label      sql.NullString `json:"label"`
	Bank       sql.NullString `json:"bank"`
	HolderName sql.NullString `json:"holderName"`
	Expiry     sql.NullString `json:"expiry"`
	CardLimit  sql.NullInt64  `json:"cardLimit"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
	OwnerID    sql.NullString `json:"ownerId"`
	AssignedAt sql.NullTime   `json:"assignedAt"`
}

func (q *Queries) ListAllBusinessCards(ctx context.Context) ([]ListAllBusinessCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBusinessCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBusinessCardsRow
	for rows.Next() {
		var i ListAllBusinessCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Last4,
			&i.Label,
			&i.Bank,
			&i.HolderName,
			&i.Expiry,
			&i.CardLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessCardAssignments = `-- name: ListBusinessCardAssignments :many
SELECT
  id, card_id, user_id, assigned_by, assigned_at, released_at
FROM
  business_card_assignments
WHERE
  card_id = ?
ORDER BY
  assigned_at DESC,
  id DESC
`

func (q *Queries) ListBusinessCardAssignments(ctx context.Context, cardID string) ([]BusinessCardAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessCardAssignments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessCardAssignment
	for rows.Next() {
		var i BusinessCardAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessCardsByUser = `-- name: ListBusinessCardsByUser :many
SELECT
  c.id,
  c.last4,
  c.label,
  c.bank,
  c.holder_name,
  c.expiry,
  c.card_limit,
  c.status,
  c.created_at,
  c.updated_at,
  a.user_id AS owner_id,
  a.assigned_at AS assigned_at
FROM
  business_cards c
  JOIN business_card_assignments a ON a.card_id = c.id
  AND a.released_at IS NULL
WHERE
  a.user_id = ?
ORDER BY
  c.created_at DESC
`

type ListBusinessCardsByUserRow struct {
	ID         string         `json:"id"`
	Last4      string         `json:"last4"`
	Label      sql.NullString `json:"label"`
	Bank       sql.NullString `json:"bank"`
	HolderName sql.NullString `json:"holderName"`
	Expiry     sql.NullString `json:"expiry"`
	CardLimit  sql.NullInt64  `json:"cardLimit"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
	OwnerID    string         `json:"ownerId"`
	AssignedAt time.Time      `json:"assignedAt"`
}

func (q *Queries) ListBusinessCardsByUser(ctx context.Context, userID string) ([]ListBusinessCardsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBusinessCardsByUserRow
	for rows.Next() {
		var i ListBusinessCardsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Last4,
			&i.Label,
			&i.Bank,
			&i.HolderName,
			&i.Expiry,
			&i.CardLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByBusinessCard = `-- name: ListReceiptsByBusinessCard :many
SELECT
  id, user_id, ticket_date, total_sum, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at, shift_number, kkt_reg_id, fiscal_document_format_ver, machine_number, retail_place, operator, prepaid_sum, nds22, has_paper, fiscal_drive_number, fiscal_document_number, fiscal_sign, seller_inn, object_id, categories_manual, business_card_id
FROM
  receipts
WHERE
  business_card_id = ?
ORDER BY
  ticket_date DESC
`

func (q *Queries) ListReceiptsByBusinessCard(ctx context.Context, businessCardID sql.NullString) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByBusinessCard, businessCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TicketDate,
			&i.TotalSum,
			&i.SellerName,
			&i.OperationType,
			&i.RetailPlaceAddress,
			&i.RequestNumber,
			&i.CashTotalSum,
			&i.EcashTotalSum,
			&i.TaxationType,
			&i.Nds20,
			&i.Nds10,
			&i.Nds0,
			&i.NdsNo,
			&i.RawQr,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShiftNumber,
			&i.KktRegID,
			&i.FiscalDocumentFormatVer,
			&i.MachineNumber,
			&i.RetailPlace,
			&i.Operator,
			&i.PrepaidSum,
			&i.Nds22,
			&i.HasPaper,
			&i.FiscalDriveNumber,
			&i.FiscalDocumentNumber,
			&i.FiscalSign,
			&i.SellerInn,
			&i.ObjectID,
			&i.CategoriesManual,
			&i.BusinessCardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBusinessCardAssignment = `-- name: ReleaseBusinessCardAssignment :exec
UPDATE business_card_assignments
SET
  released_at = ?
WHERE
  card_id = ?
  AND released_at IS NULL
`

type ReleaseBusinessCardAssignmentParams struct {
	ReleasedAt sql.NullTime `json:"releasedAt"`
	CardID     string       `json:"cardId"`
}

func (q *Queries) ReleaseBusinessCardAssignment(ctx context.Context, arg ReleaseBusinessCardAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, releaseBusinessCardAssignment, arg.ReleasedAt, arg.CardID)
	return err
}

const updateBusinessCard = `-- name: UpdateBusinessCard :exec
UPDATE business_cards
SET
  card_number_enc = ?,
  last4 = ?,
  label = ?,
  bank = ?,
  holder_name = ?,
  expiry = ?,
  card_limit = ?,
  status = ?,
  updated_at = ?
WHERE
  id = ?
`

type UpdateBusinessCardParams struct {
	CardNumberEnc string         `json:"cardNumberEnc"`
	Last4         string         `json:"last4"`
	Label         sql.NullString `json:"label"`
	Bank          sql.NullString `json:"bank"`
	HolderName    sql.NullString `json:"holderName"`
	Expiry        sql.NullString `json:"expiry"`
	CardLimit     sql.NullInt64  `json:"cardLimit"`
	Status        string         `json:"status"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateBusinessCard(ctx context.Context, arg UpdateBusinessCardParams) error {
	_, err := q.db.ExecContext(ctx, updateBusinessCard,
		arg.CardNumberEnc,
		arg.Last4,
		arg.Label,
		arg.Bank,
		arg.HolderName,
		arg.Expiry,
		arg.CardLimit,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
