// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_messages.sql

package repo

import (
	"context"
	"database/sql"
)

const createChatMessage = `-- name: CreateChatMessage :execresult
INSERT INTO
  chat_messages (
    chat_id,
    sender_user_id,
    body,
    entity_type,
    entity_id,
    entity_title,
    entity_subtitle,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, UTC_TIMESTAMP())
`

type CreateChatMessageParams struct {
	ChatID         string         `json:"chatId"`
	SenderUserID   string         `json:"senderUserId"`
	Body           string         `json:"body"`
	EntityType     sql.NullString `json:"entityType"`
	EntityID       sql.NullString `json:"entityId"`
	EntityTitle    sql.NullString `json:"entityTitle"`
	EntitySubtitle sql.NullString `json:"entitySubtitle"`
}

// ============================================
// chat_messages queries
// ============================================
func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatMessage,
		arg.ChatID,
		arg.SenderUserID,
		arg.Body,
		arg.EntityType,
		arg.EntityID,
		arg.EntityTitle,
		arg.EntitySubtitle,
	)
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT
  id, chat_id, sender_user_id, body, is_deleted, entity_type, entity_id, entity_title, entity_subtitle, deleted_at, created_at
FROM
  chat_messages
WHERE
  id = ?
`

func (q *Queries) GetChatMessageByID(ctx context.Context, id uint64) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getChatMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderUserID,
		&i.Body,
		&i.IsDeleted,
		&i.EntityType,
		&i.EntityID,
		&i.EntityTitle,
		&i.EntitySubtitle,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT
  id, chat_id, sender_user_id, body, is_deleted, entity_type, entity_id, entity_title, entity_subtitle, deleted_at, created_at
FROM
  chat_messages
WHERE
  chat_id = ?
  AND is_deleted = FALSE
  AND (? IS NULL OR id < ?)
ORDER BY
  id DESC
LIMIT
  ?
`

type ListChatMessagesParams struct {
	ChatID   string        `json:"chatId"`
	BeforeID sql.NullInt64 `json:"beforeId"`
	Limit    int32         `json:"limit"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages,
		arg.ChatID,
		arg.BeforeID,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderUserID,
			&i.Body,
			&i.IsDeleted,
			&i.EntityType,
			&i.EntityID,
			&i.EntityTitle,
			&i.EntitySubtitle,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :exec
UPDATE chat_messages
SET
  is_deleted = TRUE,
  deleted_at = UTC_TIMESTAMP()
WHERE
  id = ?
`

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, softDeleteChatMessage, id)
	return err
}
