// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_participants.sql

package repo

import (
	"context"
	"database/sql"
)

const addChatParticipant = `-- name: AddChatParticipant :exec
INSERT INTO
  chat_participants (chat_id, user_id, role, joined_at)
VALUES
  (?, ?, ?, UTC_TIMESTAMP())
`

type AddChatParticipantParams struct {
	ChatID string               `json:"chatId"`
	UserID string               `json:"userId"`
	Role   ChatParticipantsRole `json:"role"`
}

// ============================================
// chat_participants queries
// ============================================
func (q *Queries) AddChatParticipant(ctx context.Context, arg AddChatParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addChatParticipant, arg.ChatID, arg.UserID, arg.Role)
	return err
}

const countUnreadChatMessages = `-- name: CountUnreadChatMessages :one
SELECT
  COUNT(*)
FROM
  chat_messages m
  INNER JOIN chat_participants cp ON cp.chat_id = m.chat_id
WHERE
  cp.chat_id = ?
  AND cp.user_id = ?
  AND m.is_deleted = FALSE
  AND m.id > COALESCE(cp.last_read_message_id, 0)
`

type CountUnreadChatMessagesParams struct {
	ChatID string `json:"chatId"`
	UserID string `json:"userId"`
}

func (q *Queries) CountUnreadChatMessages(ctx context.Context, arg CountUnreadChatMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadChatMessages, arg.ChatID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChatParticipant = `-- name: GetChatParticipant :one
SELECT
  chat_id, user_id, role, last_read_message_id, last_read_at, joined_at, muted, vk_muted
FROM
  chat_participants
WHERE
  chat_id = ?
  AND user_id = ?
`

type GetChatParticipantParams struct {
	ChatID string `json:"chatId"`
	UserID string `json:"userId"`
}

func (q *Queries) GetChatParticipant(ctx context.Context, arg GetChatParticipantParams) (ChatParticipant, error) {
	row := q.db.QueryRowContext(ctx, getChatParticipant, arg.ChatID, arg.UserID)
	var i ChatParticipant
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.Role,
		&i.LastReadMessageID,
		&i.LastReadAt,
		&i.JoinedAt,
		&i.Muted,
		&i.VkMuted,
	)
	return i, err
}

const listChatParticipants = `-- name: ListChatParticipants :many
SELECT
  chat_id, user_id, role, last_read_message_id, last_read_at, joined_at, muted, vk_muted
FROM
  chat_participants
WHERE
  chat_id = ?
ORDER BY
  joined_at
`

func (q *Queries) ListChatParticipants(ctx context.Context, chatID string) ([]ChatParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listChatParticipants, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.Role,
			&i.LastReadMessageID,
			&i.LastReadAt,
			&i.JoinedAt,
			&i.Muted,
			&i.VkMuted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChatRead = `-- name: MarkChatRead :exec
UPDATE chat_participants
SET
  last_read_message_id = ?,
  last_read_at = UTC_TIMESTAMP()
WHERE
  chat_id = ?
  AND user_id = ?
`

type MarkChatReadParams struct {
	LastReadMessageID sql.NullInt64 `json:"lastReadMessageId"`
	ChatID            string        `json:"chatId"`
	UserID            string        `json:"userId"`
}

func (q *Queries) MarkChatRead(ctx context.Context, arg MarkChatReadParams) error {
	_, err := q.db.ExecContext(ctx, markChatRead, arg.LastReadMessageID, arg.ChatID, arg.UserID)
	return err
}

const removeChatParticipant = `-- name: RemoveChatParticipant :exec
DELETE FROM chat_participants
WHERE
  chat_id = ?
  AND user_id = ?
`

type RemoveChatParticipantParams struct {
	ChatID string `json:"chatId"`
	UserID string `json:"userId"`
}

func (q *Queries) RemoveChatParticipant(ctx context.Context, arg RemoveChatParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeChatParticipant, arg.ChatID, arg.UserID)
	return err
}

const setChatParticipantMuted = `-- name: SetChatParticipantMuted :exec
UPDATE chat_participants
SET
  muted = ?
WHERE
  chat_id = ?
  AND user_id = ?
`

type SetChatParticipantMutedParams struct {
	Muted  bool   `json:"muted"`
	ChatID string `json:"chatId"`
	UserID string `json:"userId"`
}

func (q *Queries) SetChatParticipantMuted(ctx context.Context, arg SetChatParticipantMutedParams) error {
	_, err := q.db.ExecContext(ctx, setChatParticipantMuted, arg.Muted, arg.ChatID, arg.UserID)
	return err
}

const setChatParticipantVKMuted = `-- name: SetChatParticipantVKMuted :exec
UPDATE chat_participants
SET
  vk_muted = ?
WHERE
  chat_id = ?
  AND user_id = ?
`

type SetChatParticipantVKMutedParams struct {
	VkMuted bool   `json:"vkMuted"`
	ChatID  string `json:"chatId"`
	UserID  string `json:"userId"`
}

func (q *Queries) SetChatParticipantVKMuted(ctx context.Context, arg SetChatParticipantVKMutedParams) error {
	_, err := q.db.ExecContext(ctx, setChatParticipantVKMuted, arg.VkMuted, arg.ChatID, arg.UserID)
	return err
}

const updateChatParticipantRole = `-- name: UpdateChatParticipantRole :exec
UPDATE chat_participants
SET
  role = ?
WHERE
  chat_id = ?
  AND user_id = ?
`

type UpdateChatParticipantRoleParams struct {
	Role   ChatParticipantsRole `json:"role"`
	ChatID string               `json:"chatId"`
	UserID string               `json:"userId"`
}

func (q *Queries) UpdateChatParticipantRole(ctx context.Context, arg UpdateChatParticipantRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateChatParticipantRole, arg.Role, arg.ChatID, arg.UserID)
	return err
}
