// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createChat = `-- name: CreateChat :exec
INSERT INTO
  chats (id, type, name, entity_type, entity_id, created_by_user_id)
VALUES
  (?, ?, ?, ?, ?, ?)
`

type CreateChatParams struct {
	ID              string         `json:"id"`
	Type            ChatsType      `json:"type"`
	Name            sql.NullString `json:"name"`
	EntityType      sql.NullString `json:"entityType"`
	EntityID        sql.NullString `json:"entityId"`
	CreatedByUserID string         `json:"createdByUserId"`
}

// ============================================
// chats queries
// ============================================
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.ExecContext(ctx, createChat,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.EntityType,
		arg.EntityID,
		arg.CreatedByUserID,
	)
	return err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE
  id = ?
`

// Каскадно удаляет chat_participants и chat_messages (ON DELETE CASCADE,
// см. миграцию 011_add_chats.sql).
func (q *Queries) DeleteChat(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChat, id)
	return err
}

const getChatByEntity = `-- name: GetChatByEntity :one
SELECT
  id, type, name, entity_type, entity_id, created_by_user_id, last_message_at, created_at, updated_at
FROM
  chats
WHERE
  entity_type = ?
  AND entity_id = ?
`

type GetChatByEntityParams struct {
	EntityType sql.NullString `json:"entityType"`
	EntityID   sql.NullString `json:"entityId"`
}

func (q *Queries) GetChatByEntity(ctx context.Context, arg GetChatByEntityParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByEntity, arg.EntityType, arg.EntityID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedByUserID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT
  id, type, name, entity_type, entity_id, created_by_user_id, last_message_at, created_at, updated_at
FROM
  chats
WHERE
  id = ?
`

func (q *Queries) GetChatByID(ctx context.Context, id string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedByUserID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatsByUser = `-- name: ListChatsByUser :many
SELECT
  c.id,
  c.type,
  c.name,
  c.entity_type,
  c.entity_id,
  c.created_by_user_id,
  c.last_message_at,
  c.created_at,
  c.updated_at,
  cp.role,
  cp.last_read_message_id,
  cp.last_read_at
FROM
  chats c
  INNER JOIN chat_participants cp ON cp.chat_id = c.id
WHERE
  cp.user_id = ?
ORDER BY
  c.last_message_at DESC,
  c.created_at DESC
`

type ListChatsByUserRow struct {
	ID                string               `json:"id"`
	Type              ChatsType            `json:"type"`
	Name              sql.NullString       `json:"name"`
	EntityType        sql.NullString       `json:"entityType"`
	EntityID          sql.NullString       `json:"entityId"`
	CreatedByUserID   string               `json:"createdByUserId"`
	LastMessageAt     sql.NullTime         `json:"lastMessageAt"`
	CreatedAt         time.Time            `json:"createdAt"`
	UpdatedAt         time.Time            `json:"updatedAt"`
	Role              ChatParticipantsRole `json:"role"`
	LastReadMessageID sql.NullInt64        `json:"lastReadMessageId"`
	LastReadAt        sql.NullTime         `json:"lastReadAt"`
}

func (q *Queries) ListChatsByUser(ctx context.Context, userID string) ([]ListChatsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatsByUserRow
	for rows.Next() {
		var i ListChatsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedByUserID,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.LastReadMessageID,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChatLastMessage = `-- name: TouchChatLastMessage :exec
UPDATE chats
SET
  last_message_at = ?
WHERE
  id = ?
`

type TouchChatLastMessageParams struct {
	LastMessageAt sql.NullTime `json:"lastMessageAt"`
	ID            string       `json:"id"`
}

func (q *Queries) TouchChatLastMessage(ctx context.Context, arg TouchChatLastMessageParams) error {
	_, err := q.db.ExecContext(ctx, touchChatLastMessage, arg.LastMessageAt, arg.ID)
	return err
}

const updateChatName = `-- name: UpdateChatName :exec
UPDATE chats
SET
  name = ?
WHERE
  id = ?
`

type UpdateChatNameParams struct {
	Name sql.NullString `json:"name"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateChatName(ctx context.Context, arg UpdateChatNameParams) error {
	_, err := q.db.ExecContext(ctx, updateChatName, arg.Name, arg.ID)
	return err
}
