// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: day_types.sql

package repo

import (
	"context"
)

const createDayType = `-- name: CreateDayType :exec
INSERT INTO day_types (name, system_name, is_work_day, affects_vacation, color_code) VALUES (?, ?, ?, ?, ?)
`

type CreateDayTypeParams struct {
	Name            string `json:"name"`
	SystemName      string `json:"systemName"`
	IsWorkDay       bool   `json:"isWorkDay"`
	AffectsVacation bool   `json:"affectsVacation"`
	ColorCode       string `json:"colorCode"`
}

func (q *Queries) CreateDayType(ctx context.Context, arg CreateDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, createDayType,
		arg.Name,
		arg.SystemName,
		arg.IsWorkDay,
		arg.AffectsVacation,
		arg.ColorCode,
	)
	return err
}

const deleteDayType = `-- name: DeleteDayType :exec
DELETE FROM day_types WHERE id = ?
`

func (q *Queries) DeleteDayType(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDayType, id)
	return err
}

const getDayTypeByID = `-- name: GetDayTypeByID :one
SELECT id, name, system_name, is_work_day, affects_vacation, color_code, created_at, updated_at FROM day_types WHERE id = ?
`

func (q *Queries) GetDayTypeByID(ctx context.Context, id string) (DayType, error) {
	row := q.db.QueryRowContext(ctx, getDayTypeByID, id)
	var i DayType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemName,
		&i.IsWorkDay,
		&i.AffectsVacation,
		&i.ColorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDayTypes = `-- name: GetDayTypes :many

SELECT id, name, system_name, is_work_day, affects_vacation, color_code, created_at, updated_at FROM day_types
`

// ============================================
// day_types queries
// ============================================
func (q *Queries) GetDayTypes(ctx context.Context) ([]DayType, error) {
	rows, err := q.db.QueryContext(ctx, getDayTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayType
	for rows.Next() {
		var i DayType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemName,
			&i.IsWorkDay,
			&i.AffectsVacation,
			&i.ColorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAffectsVacationDayType = `-- name: UpdateAffectsVacationDayType :exec
UPDATE day_types SET affects_vacation = ? WHERE id = ?
`

type UpdateAffectsVacationDayTypeParams struct {
	AffectsVacation bool   `json:"affectsVacation"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateAffectsVacationDayType(ctx context.Context, arg UpdateAffectsVacationDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateAffectsVacationDayType, arg.AffectsVacation, arg.ID)
	return err
}

const updateColorCodeDayType = `-- name: UpdateColorCodeDayType :exec
UPDATE day_types SET color_code = ? WHERE id = ?
`

type UpdateColorCodeDayTypeParams struct {
	ColorCode string `json:"colorCode"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateColorCodeDayType(ctx context.Context, arg UpdateColorCodeDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateColorCodeDayType, arg.ColorCode, arg.ID)
	return err
}

const updateDayType = `-- name: UpdateDayType :exec
UPDATE day_types SET name = ?, system_name = ?, is_work_day = ?, affects_vacation = ?, color_code = ? WHERE id = ?
`

type UpdateDayTypeParams struct {
	Name            string `json:"name"`
	SystemName      string `json:"systemName"`
	IsWorkDay       bool   `json:"isWorkDay"`
	AffectsVacation bool   `json:"affectsVacation"`
	ColorCode       string `json:"colorCode"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateDayType(ctx context.Context, arg UpdateDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateDayType,
		arg.Name,
		arg.SystemName,
		arg.IsWorkDay,
		arg.AffectsVacation,
		arg.ColorCode,
		arg.ID,
	)
	return err
}

const updateIsWorkDayType = `-- name: UpdateIsWorkDayType :exec
UPDATE day_types SET is_work_day = ? WHERE id = ?
`

type UpdateIsWorkDayTypeParams struct {
	IsWorkDay bool   `json:"isWorkDay"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateIsWorkDayType(ctx context.Context, arg UpdateIsWorkDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateIsWorkDayType, arg.IsWorkDay, arg.ID)
	return err
}

const updateNameDayType = `-- name: UpdateNameDayType :exec
UPDATE day_types SET name = ? WHERE id = ?
`

type UpdateNameDayTypeParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateNameDayType(ctx context.Context, arg UpdateNameDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateNameDayType, arg.Name, arg.ID)
	return err
}

const updateSystemNameDayType = `-- name: UpdateSystemNameDayType :exec
UPDATE day_types SET system_name = ? WHERE id = ?
`

type UpdateSystemNameDayTypeParams struct {
	SystemName string `json:"systemName"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSystemNameDayType(ctx context.Context, arg UpdateSystemNameDayTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemNameDayType, arg.SystemName, arg.ID)
	return err
}
