// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO
  files (
    id,
    original_name,
    storage_path,
    mime_type,
    file_type,
    category_id,
    size_bytes,
    checksum,
    uploaded_by_user_id
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	CategoryID       sql.NullString `json:"categoryId"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.OriginalName,
		arg.StoragePath,
		arg.MimeType,
		arg.FileType,
		arg.CategoryID,
		arg.SizeBytes,
		arg.Checksum,
		arg.UploadedByUserID,
	)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT
  id,
  original_name,
  storage_path,
  mime_type,
  file_type,
  category_id,
  size_bytes,
  checksum,
  uploaded_by_user_id,
  is_deleted,
  deleted_at,
  created_at,
  updated_at
FROM
  files
WHERE
  id = ?
  AND is_deleted = FALSE
`

type GetFileByIDRow struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	CategoryID       sql.NullString `json:"categoryId"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
	IsDeleted        bool           `json:"isDeleted"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}

func (q *Queries) GetFileByID(ctx context.Context, id string) (GetFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i GetFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileType,
		&i.CategoryID,
		&i.SizeBytes,
		&i.Checksum,
		&i.UploadedByUserID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteFile = `-- name: HardDeleteFile :exec
DELETE FROM files
WHERE
  id = ?
`

func (q *Queries) HardDeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteFile, id)
	return err
}

const listFilesByCategory = `-- name: ListFilesByCategory :many
SELECT
  id,
  original_name,
  storage_path,
  mime_type,
  file_type,
  category_id,
  size_bytes,
  checksum,
  uploaded_by_user_id,
  is_deleted,
  deleted_at,
  created_at,
  updated_at
FROM
  files
WHERE
  category_id = ?
  AND is_deleted = FALSE
  AND (? IS NULL OR YEAR(created_at) = CAST(? AS SIGNED))
ORDER BY
  created_at DESC
`

type ListFilesByCategoryParams struct {
	CategoryID sql.NullString `json:"categoryId"`
	Year       sql.NullInt64  `json:"year"`
}

type ListFilesByCategoryRow struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	CategoryID       sql.NullString `json:"categoryId"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
	IsDeleted        bool           `json:"isDeleted"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}

func (q *Queries) ListFilesByCategory(ctx context.Context, arg ListFilesByCategoryParams) ([]ListFilesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByCategory, arg.CategoryID, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByCategoryRow
	for rows.Next() {
		var i ListFilesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileType,
			&i.CategoryID,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedByUserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByUploader = `-- name: ListFilesByUploader :many
SELECT
  id,
  original_name,
  storage_path,
  mime_type,
  file_type,
  category_id,
  size_bytes,
  checksum,
  uploaded_by_user_id,
  is_deleted,
  deleted_at,
  created_at,
  updated_at
FROM
  files
WHERE
  uploaded_by_user_id = ?
  AND is_deleted = FALSE
  AND (? IS NULL OR YEAR(created_at) = CAST(? AS SIGNED))
ORDER BY
  created_at DESC
`

type ListFilesByUploaderParams struct {
	UploadedByUserID string        `json:"uploadedByUserId"`
	Year             sql.NullInt64 `json:"year"`
}

type ListFilesByUploaderRow struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	CategoryID       sql.NullString `json:"categoryId"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
	IsDeleted        bool           `json:"isDeleted"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}

func (q *Queries) ListFilesByUploader(ctx context.Context, arg ListFilesByUploaderParams) ([]ListFilesByUploaderRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUploader, arg.UploadedByUserID, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByUploaderRow
	for rows.Next() {
		var i ListFilesByUploaderRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileType,
			&i.CategoryID,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedByUserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files
SET
  is_deleted = TRUE,
  deleted_at = CURRENT_TIMESTAMP
WHERE
  id = ?
  AND is_deleted = FALSE
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteFile, id)
	return err
}

const updateFileCategoryAssignment = `-- name: UpdateFileCategoryAssignment :exec
UPDATE files
SET
  category_id = ?
WHERE
  id = ?
  AND is_deleted = FALSE
`

type UpdateFileCategoryAssignmentParams struct {
	CategoryID sql.NullString `json:"categoryId"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateFileCategoryAssignment(ctx context.Context, arg UpdateFileCategoryAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, updateFileCategoryAssignment, arg.CategoryID, arg.ID)
	return err
}
