// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_entity_refs.sql

package repo

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createFileEntityRef = `-- name: CreateFileEntityRef :exec
INSERT INTO
  file_entity_refs (file_id, entity_type, entity_id)
VALUES
  (?, ?, ?)
`

type CreateFileEntityRefParams struct {
	FileID     string `json:"fileId"`
	EntityType string `json:"entityType"`
	EntityID   string `json:"entityId"`
}

func (q *Queries) CreateFileEntityRef(ctx context.Context, arg CreateFileEntityRefParams) error {
	_, err := q.db.ExecContext(ctx, createFileEntityRef, arg.FileID, arg.EntityType, arg.EntityID)
	return err
}

const deleteAllFileEntityRefsByFile = `-- name: DeleteAllFileEntityRefsByFile :exec
DELETE FROM file_entity_refs
WHERE
  file_id = ?
`

func (q *Queries) DeleteAllFileEntityRefsByFile(ctx context.Context, fileID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllFileEntityRefsByFile, fileID)
	return err
}

const listFilesByEntity = `-- name: ListFilesByEntity :many
SELECT
  f.id,
  f.original_name,
  f.storage_path,
  f.mime_type,
  f.file_type,
  f.category_id,
  f.size_bytes,
  f.checksum,
  f.uploaded_by_user_id,
  f.is_deleted,
  f.deleted_at,
  f.created_at,
  f.updated_at
FROM
  files f
  INNER JOIN file_entity_refs r ON r.file_id = f.id
WHERE
  r.entity_type = ?
  AND r.entity_id = ?
  AND f.is_deleted = FALSE
  AND (? IS NULL OR YEAR(f.created_at) = CAST(? AS SIGNED))
ORDER BY
  r.created_at DESC
`

type ListFilesByEntityParams struct {
	EntityType string        `json:"entityType"`
	EntityID   string        `json:"entityId"`
	Year       sql.NullInt64 `json:"year"`
}

type ListFilesByEntityRow struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	CategoryID       sql.NullString `json:"categoryId"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
	IsDeleted        bool           `json:"isDeleted"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}

func (q *Queries) ListFilesByEntity(ctx context.Context, arg ListFilesByEntityParams) ([]ListFilesByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Year,
		arg.Year,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByEntityRow
	for rows.Next() {
		var i ListFilesByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileType,
			&i.CategoryID,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedByUserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByEntityIDs = `-- name: ListFilesByEntityIDs :many
SELECT
  f.id,
  f.original_name,
  f.mime_type,
  f.file_type,
  f.size_bytes,
  r.entity_id
FROM
  files f
  INNER JOIN file_entity_refs r ON r.file_id = f.id
WHERE
  r.entity_type = ?
  AND r.entity_id IN (/*SLICE:entity_ids*/?)
  AND f.is_deleted = FALSE
ORDER BY
  r.created_at
`

type ListFilesByEntityIDsParams struct {
	EntityType string   `json:"entityType"`
	EntityIds  []string `json:"entityIds"`
}

type ListFilesByEntityIDsRow struct {
	ID           string `json:"id"`
	OriginalName string `json:"originalName"`
	MimeType     string `json:"mimeType"`
	FileType     string `json:"fileType"`
	SizeBytes    int64  `json:"sizeBytes"`
	EntityID     string `json:"entityId"`
}

// Вложения сразу для НЕСКОЛЬКИХ сущностей одного типа за один запрос —
// нужно, чтобы отдать список сообщений чата со вложениями без N+1
// (см. internal/chat/service.go, attachmentsForMessages).
func (q *Queries) ListFilesByEntityIDs(ctx context.Context, arg ListFilesByEntityIDsParams) ([]ListFilesByEntityIDsRow, error) {
	query := listFilesByEntityIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.EntityType)
	if len(arg.EntityIds) > 0 {
		for _, v := range arg.EntityIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:entity_ids*/?", strings.Repeat(",?", len(arg.EntityIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:entity_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByEntityIDsRow
	for rows.Next() {
		var i ListFilesByEntityIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.MimeType,
			&i.FileType,
			&i.SizeBytes,
			&i.EntityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByEntityType = `-- name: ListFilesByEntityType :many
SELECT
  f.id,
  f.original_name,
  f.storage_path,
  f.mime_type,
  f.file_type,
  f.category_id,
  f.size_bytes,
  f.checksum,
  f.uploaded_by_user_id,
  f.is_deleted,
  f.deleted_at,
  f.created_at,
  f.updated_at,
  r.entity_type,
  r.entity_id
FROM
  files f
  INNER JOIN file_entity_refs r ON r.file_id = f.id
WHERE
  r.entity_type = ?
  AND f.is_deleted = FALSE
  AND (? IS NULL OR YEAR(f.created_at) = CAST(? AS SIGNED))
ORDER BY
  r.created_at DESC
`

type ListFilesByEntityTypeParams struct {
	EntityType string        `json:"entityType"`
	Year       sql.NullInt64 `json:"year"`
}

type ListFilesByEntityTypeRow struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	CategoryID       sql.NullString `json:"categoryId"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
	IsDeleted        bool           `json:"isDeleted"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	EntityType       string         `json:"entityType"`
	EntityID         string         `json:"entityId"`
}

func (q *Queries) ListFilesByEntityType(ctx context.Context, arg ListFilesByEntityTypeParams) ([]ListFilesByEntityTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByEntityType, arg.EntityType, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByEntityTypeRow
	for rows.Next() {
		var i ListFilesByEntityTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileType,
			&i.CategoryID,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedByUserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntityType,
			&i.EntityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
