// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_categories.sql

package repo

import (
	"context"
	"database/sql"
)

const countFileCategoryChildren = `-- name: CountFileCategoryChildren :one
SELECT
  COUNT(*)
FROM
  file_categories
WHERE
  parent_id = ?
`

func (q *Queries) CountFileCategoryChildren(ctx context.Context, parentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFileCategoryChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesInCategory = `-- name: CountFilesInCategory :one
SELECT
  COUNT(*)
FROM
  files
WHERE
  category_id = ?
  AND is_deleted = FALSE
`

func (q *Queries) CountFilesInCategory(ctx context.Context, categoryID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilesInCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFileCategory = `-- name: CreateFileCategory :exec
INSERT INTO
  file_categories (id, name, parent_id, color_code, sort_order)
VALUES
  (?, ?, ?, ?, ?)
`

type CreateFileCategoryParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	ParentID  sql.NullString `json:"parentId"`
	ColorCode sql.NullString `json:"colorCode"`
	SortOrder int32          `json:"sortOrder"`
}

func (q *Queries) CreateFileCategory(ctx context.Context, arg CreateFileCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createFileCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.ColorCode,
		arg.SortOrder,
	)
	return err
}

const deleteFileCategory = `-- name: DeleteFileCategory :exec
DELETE FROM file_categories
WHERE
  id = ?
`

func (q *Queries) DeleteFileCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFileCategory, id)
	return err
}

const getFileCategories = `-- name: GetFileCategories :many
SELECT
  id, name, parent_id, color_code, sort_order, created_at, updated_at, system_name
FROM
  file_categories
ORDER BY
  sort_order,
  name
`

// ============================================
// file_categories queries
// ============================================
func (q *Queries) GetFileCategories(ctx context.Context) ([]FileCategory, error) {
	rows, err := q.db.QueryContext(ctx, getFileCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileCategory
	for rows.Next() {
		var i FileCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.ColorCode,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileCategoryByID = `-- name: GetFileCategoryByID :one
SELECT
  id, name, parent_id, color_code, sort_order, created_at, updated_at, system_name
FROM
  file_categories
WHERE
  id = ?
`

func (q *Queries) GetFileCategoryByID(ctx context.Context, id string) (FileCategory, error) {
	row := q.db.QueryRowContext(ctx, getFileCategoryByID, id)
	var i FileCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.ColorCode,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
	)
	return i, err
}

const getFileCategoryByParentAndName = `-- name: GetFileCategoryByParentAndName :one
SELECT
  id, name, parent_id, color_code, sort_order, created_at, updated_at, system_name
FROM
  file_categories
WHERE
  name = ?
  AND parent_id <=> ?
`

type GetFileCategoryByParentAndNameParams struct {
	Name     string         `json:"name"`
	ParentID sql.NullString `json:"parentId"`
}

func (q *Queries) GetFileCategoryByParentAndName(ctx context.Context, arg GetFileCategoryByParentAndNameParams) (FileCategory, error) {
	row := q.db.QueryRowContext(ctx, getFileCategoryByParentAndName, arg.Name, arg.ParentID)
	var i FileCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.ColorCode,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
	)
	return i, err
}

const getFileCategoryBySystemName = `-- name: GetFileCategoryBySystemName :one
SELECT
  id, name, parent_id, color_code, sort_order, created_at, updated_at, system_name
FROM
  file_categories
WHERE
  system_name = ?
`

func (q *Queries) GetFileCategoryBySystemName(ctx context.Context, systemName sql.NullString) (FileCategory, error) {
	row := q.db.QueryRowContext(ctx, getFileCategoryBySystemName, systemName)
	var i FileCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.ColorCode,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemName,
	)
	return i, err
}

const updateFileCategory = `-- name: UpdateFileCategory :exec
UPDATE file_categories
SET
  name = ?,
  parent_id = ?,
  color_code = ?,
  sort_order = ?
WHERE
  id = ?
`

type UpdateFileCategoryParams struct {
	Name      string         `json:"name"`
	ParentID  sql.NullString `json:"parentId"`
	ColorCode sql.NullString `json:"colorCode"`
	SortOrder int32          `json:"sortOrder"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateFileCategory(ctx context.Context, arg UpdateFileCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateFileCategory,
		arg.Name,
		arg.ParentID,
		arg.ColorCode,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
