// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package repo

import (
	"context"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, original_name, storage_path, mime_type, file_type, size_bytes, checksum, uploaded_by_user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	ID               string `json:"id"`
	OriginalName     string `json:"originalName"`
	StoragePath      string `json:"storagePath"`
	MimeType         string `json:"mimeType"`
	FileType         string `json:"fileType"`
	SizeBytes        int64  `json:"sizeBytes"`
	Checksum         string `json:"checksum"`
	UploadedByUserID string `json:"uploadedByUserId"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.OriginalName,
		arg.StoragePath,
		arg.MimeType,
		arg.FileType,
		arg.SizeBytes,
		arg.Checksum,
		arg.UploadedByUserID,
	)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, original_name, storage_path, mime_type, file_type, size_bytes, checksum,
       uploaded_by_user_id, is_deleted, deleted_at, created_at, updated_at
FROM files
WHERE id = ? AND is_deleted = FALSE
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileType,
		&i.SizeBytes,
		&i.Checksum,
		&i.UploadedByUserID,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesByUploader = `-- name: ListFilesByUploader :many
SELECT id, original_name, storage_path, mime_type, file_type, size_bytes, checksum,
       uploaded_by_user_id, is_deleted, deleted_at, created_at, updated_at
FROM files
WHERE uploaded_by_user_id = ? AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListFilesByUploader(ctx context.Context, uploadedByUserID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUploader, uploadedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileType,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedByUserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const hardDeleteFile = `-- name: HardDeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) HardDeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteFile, id)
	return err
}
