// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_entity_refs.sql

package repo

import (
	"context"
)

const createFileEntityRef = `-- name: CreateFileEntityRef :exec
INSERT INTO file_entity_refs (file_id, entity_type, entity_id)
VALUES (?, ?, ?)
`

type CreateFileEntityRefParams struct {
	FileID     string `json:"fileId"`
	EntityType string `json:"entityType"`
	EntityID   string `json:"entityId"`
}

func (q *Queries) CreateFileEntityRef(ctx context.Context, arg CreateFileEntityRefParams) error {
	_, err := q.db.ExecContext(ctx, createFileEntityRef, arg.FileID, arg.EntityType, arg.EntityID)
	return err
}

const listFilesByEntity = `-- name: ListFilesByEntity :many
SELECT f.id, f.original_name, f.storage_path, f.mime_type, f.file_type, f.size_bytes, f.checksum,
       f.uploaded_by_user_id, f.is_deleted, f.deleted_at, f.created_at, f.updated_at
FROM files f
INNER JOIN file_entity_refs r ON r.file_id = f.id
WHERE r.entity_type = ? AND r.entity_id = ? AND f.is_deleted = FALSE
ORDER BY r.created_at DESC
`

type ListFilesByEntityParams struct {
	EntityType string `json:"entityType"`
	EntityID   string `json:"entityId"`
}

func (q *Queries) ListFilesByEntity(ctx context.Context, arg ListFilesByEntityParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileType,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedByUserID,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const deleteAllFileEntityRefsByFile = `-- name: DeleteAllFileEntityRefsByFile :exec
DELETE FROM file_entity_refs WHERE file_id = ?
`

func (q *Queries) DeleteAllFileEntityRefsByFile(ctx context.Context, fileID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllFileEntityRefsByFile, fileID)
	return err
}
