// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type SystemSettingsSettingType string

const (
	SystemSettingsSettingTypeString  SystemSettingsSettingType = "string"
	SystemSettingsSettingTypeInteger SystemSettingsSettingType = "integer"
	SystemSettingsSettingTypeBoolean SystemSettingsSettingType = "boolean"
	SystemSettingsSettingTypeFloat   SystemSettingsSettingType = "float"
	SystemSettingsSettingTypeJson    SystemSettingsSettingType = "json"
)

func (e *SystemSettingsSettingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemSettingsSettingType(s)
	case string:
		*e = SystemSettingsSettingType(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemSettingsSettingType: %T", src)
	}
	return nil
}

type NullSystemSettingsSettingType struct {
	SystemSettingsSettingType SystemSettingsSettingType `json:"systemSettingsSettingType"`
	Valid                     bool                      `json:"valid"` // Valid is true if SystemSettingsSettingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemSettingsSettingType) Scan(value interface{}) error {
	if value == nil {
		ns.SystemSettingsSettingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemSettingsSettingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemSettingsSettingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemSettingsSettingType), nil
}

type VacationsStatus string

const (
	VacationsStatusPending  VacationsStatus = "pending"
	VacationsStatusApproved VacationsStatus = "approved"
	VacationsStatusRejected VacationsStatus = "rejected"
)

func (e *VacationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VacationsStatus(s)
	case string:
		*e = VacationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VacationsStatus: %T", src)
	}
	return nil
}

type NullVacationsStatus struct {
	VacationsStatus VacationsStatus `json:"vacationsStatus"`
	Valid           bool            `json:"valid"` // Valid is true if VacationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVacationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VacationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VacationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVacationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VacationsStatus), nil
}

type WorkStandardsGender string

const (
	WorkStandardsGenderMale   WorkStandardsGender = "male"
	WorkStandardsGenderFemale WorkStandardsGender = "female"
)

func (e *WorkStandardsGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkStandardsGender(s)
	case string:
		*e = WorkStandardsGender(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkStandardsGender: %T", src)
	}
	return nil
}

type NullWorkStandardsGender struct {
	WorkStandardsGender WorkStandardsGender `json:"workStandardsGender"`
	Valid               bool                `json:"valid"` // Valid is true if WorkStandardsGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkStandardsGender) Scan(value interface{}) error {
	if value == nil {
		ns.WorkStandardsGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkStandardsGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkStandardsGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkStandardsGender), nil
}

type CalendarEvent struct {
	ID          string         `json:"id"`
	EventDate   time.Time      `json:"eventDate"`
	DayTypeID   string         `json:"dayTypeId"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type DayType struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	SystemName      string    `json:"systemName"`
	IsWorkDay       bool      `json:"isWorkDay"`
	AffectsVacation bool      `json:"affectsVacation"`
	ColorCode       string    `json:"colorCode"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type SystemSetting struct {
	ID           int32                         `json:"id"`
	SettingKey   string                        `json:"settingKey"`
	SettingValue sql.NullString                `json:"settingValue"`
	SettingType  NullSystemSettingsSettingType `json:"settingType"`
	Category     sql.NullString                `json:"category"`
	Description  sql.NullString                `json:"description"`
	IsPublic     sql.NullBool                  `json:"isPublic"`
	CreatedAt    sql.NullTime                  `json:"createdAt"`
	UpdatedAt    sql.NullTime                  `json:"updatedAt"`
}

type UserTimeEntry struct {
	ID          string       `json:"id"`
	UserID      string       `json:"userId"`
	EntryDate   time.Time    `json:"entryDate"`
	DayTypeID   string       `json:"dayTypeId"`
	HoursWorked string       `json:"hoursWorked"`
	CreatedAt   sql.NullTime `json:"createdAt"`
	UpdatedAt   sql.NullTime `json:"updatedAt"`
}

type Vacation struct {
	ID          string              `json:"id"`
	UserID      string              `json:"userId"`
	StartDate   time.Time           `json:"startDate"`
	EndDate     time.Time           `json:"endDate"`
	TotalDays   int32               `json:"totalDays"`
	Description sql.NullString      `json:"description"`
	Status      NullVacationsStatus `json:"status"`
	CreatedAt   sql.NullTime        `json:"createdAt"`
	UpdatedAt   sql.NullTime        `json:"updatedAt"`
}

type WorkStandard struct {
	ID            string              `json:"id"`
	UserID        sql.NullString      `json:"userId"`
	Month         int32               `json:"month"`
	Year          int32               `json:"year"`
	StandardHours int32               `json:"standardHours"`
	StandardDays  int32               `json:"standardDays"`
	Gender        WorkStandardsGender `json:"gender"`
	CreatedAt     sql.NullTime        `json:"createdAt"`
	UpdatedAt     sql.NullTime        `json:"updatedAt"`
}
