// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ChatParticipantsRole string

const (
	ChatParticipantsRoleMember ChatParticipantsRole = "member"
	ChatParticipantsRoleAdmin  ChatParticipantsRole = "admin"
)

func (e *ChatParticipantsRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatParticipantsRole(s)
	case string:
		*e = ChatParticipantsRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatParticipantsRole: %T", src)
	}
	return nil
}

type NullChatParticipantsRole struct {
	ChatParticipantsRole ChatParticipantsRole `json:"chatParticipantsRole"`
	Valid                bool                 `json:"valid"` // Valid is true if ChatParticipantsRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatParticipantsRole) Scan(value interface{}) error {
	if value == nil {
		ns.ChatParticipantsRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatParticipantsRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatParticipantsRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatParticipantsRole), nil
}

type ChatsType string

const (
	ChatsTypeDirect ChatsType = "direct"
	ChatsTypeGroup  ChatsType = "group"
)

func (e *ChatsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatsType(s)
	case string:
		*e = ChatsType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatsType: %T", src)
	}
	return nil
}

type NullChatsType struct {
	ChatsType ChatsType `json:"chatsType"`
	Valid     bool      `json:"valid"` // Valid is true if ChatsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatsType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatsType), nil
}

type NotificationsType string

const (
	NotificationsTypeInfo    NotificationsType = "info"
	NotificationsTypeSuccess NotificationsType = "success"
	NotificationsTypeWarn    NotificationsType = "warn"
	NotificationsTypeError   NotificationsType = "error"
)

func (e *NotificationsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationsType(s)
	case string:
		*e = NotificationsType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationsType: %T", src)
	}
	return nil
}

type NullNotificationsType struct {
	NotificationsType NotificationsType `json:"notificationsType"`
	Valid             bool              `json:"valid"` // Valid is true if NotificationsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationsType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationsType), nil
}

type SickLeavesStatus string

const (
	SickLeavesStatusOfficial   SickLeavesStatus = "official"
	SickLeavesStatusUnofficial SickLeavesStatus = "unofficial"
)

func (e *SickLeavesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SickLeavesStatus(s)
	case string:
		*e = SickLeavesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SickLeavesStatus: %T", src)
	}
	return nil
}

type NullSickLeavesStatus struct {
	SickLeavesStatus SickLeavesStatus `json:"sickLeavesStatus"`
	Valid            bool             `json:"valid"` // Valid is true if SickLeavesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSickLeavesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SickLeavesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SickLeavesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSickLeavesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SickLeavesStatus), nil
}

type SystemSettingsSettingType string

const (
	SystemSettingsSettingTypeString  SystemSettingsSettingType = "string"
	SystemSettingsSettingTypeInteger SystemSettingsSettingType = "integer"
	SystemSettingsSettingTypeBoolean SystemSettingsSettingType = "boolean"
	SystemSettingsSettingTypeFloat   SystemSettingsSettingType = "float"
	SystemSettingsSettingTypeJson    SystemSettingsSettingType = "json"
)

func (e *SystemSettingsSettingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemSettingsSettingType(s)
	case string:
		*e = SystemSettingsSettingType(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemSettingsSettingType: %T", src)
	}
	return nil
}

type NullSystemSettingsSettingType struct {
	SystemSettingsSettingType SystemSettingsSettingType `json:"systemSettingsSettingType"`
	Valid                     bool                      `json:"valid"` // Valid is true if SystemSettingsSettingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemSettingsSettingType) Scan(value interface{}) error {
	if value == nil {
		ns.SystemSettingsSettingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemSettingsSettingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemSettingsSettingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemSettingsSettingType), nil
}

type VacationsStatus string

const (
	VacationsStatusPending  VacationsStatus = "pending"
	VacationsStatusApproved VacationsStatus = "approved"
	VacationsStatusRejected VacationsStatus = "rejected"
)

func (e *VacationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VacationsStatus(s)
	case string:
		*e = VacationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VacationsStatus: %T", src)
	}
	return nil
}

type NullVacationsStatus struct {
	VacationsStatus VacationsStatus `json:"vacationsStatus"`
	Valid           bool            `json:"valid"` // Valid is true if VacationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVacationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VacationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VacationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVacationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VacationsStatus), nil
}

type CalendarEvent struct {
	ID          string         `json:"id"`
	EventDate   time.Time      `json:"eventDate"`
	DayTypeID   string         `json:"dayTypeId"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type Chat struct {
	ID              string         `json:"id"`
	Type            ChatsType      `json:"type"`
	Name            sql.NullString `json:"name"`
	EntityType      sql.NullString `json:"entityType"`
	EntityID        sql.NullString `json:"entityId"`
	CreatedByUserID string         `json:"createdByUserId"`
	LastMessageAt   sql.NullTime   `json:"lastMessageAt"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

type ChatMessage struct {
	ID           uint64       `json:"id"`
	ChatID       string       `json:"chatId"`
	SenderUserID string       `json:"senderUserId"`
	Body         string       `json:"body"`
	IsDeleted    bool         `json:"isDeleted"`
	DeletedAt    sql.NullTime `json:"deletedAt"`
	CreatedAt    time.Time    `json:"createdAt"`
}

type ChatParticipant struct {
	ChatID            string               `json:"chatId"`
	UserID            string               `json:"userId"`
	Role              ChatParticipantsRole `json:"role"`
	LastReadMessageID sql.NullInt64        `json:"lastReadMessageId"`
	LastReadAt        sql.NullTime         `json:"lastReadAt"`
	JoinedAt          time.Time            `json:"joinedAt"`
}

type DayType struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	SystemName      string    `json:"systemName"`
	IsWorkDay       bool      `json:"isWorkDay"`
	AffectsVacation bool      `json:"affectsVacation"`
	IsUserSelect    bool      `json:"isUserSelect"`
	ColorCode       string    `json:"colorCode"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type File struct {
	ID               string         `json:"id"`
	OriginalName     string         `json:"originalName"`
	StoragePath      string         `json:"storagePath"`
	MimeType         string         `json:"mimeType"`
	FileType         string         `json:"fileType"`
	SizeBytes        int64          `json:"sizeBytes"`
	Checksum         string         `json:"checksum"`
	UploadedByUserID string         `json:"uploadedByUserId"`
	IsDeleted        bool           `json:"isDeleted"`
	DeletedAt        sql.NullTime   `json:"deletedAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	CategoryID       sql.NullString `json:"categoryId"`
}

type FileCategory struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	ParentID   sql.NullString `json:"parentId"`
	ColorCode  sql.NullString `json:"colorCode"`
	SortOrder  int32          `json:"sortOrder"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
	SystemName sql.NullString `json:"systemName"`
}

type FileEntityRef struct {
	ID         int32     `json:"id"`
	FileID     string    `json:"fileId"`
	EntityType string    `json:"entityType"`
	EntityID   string    `json:"entityId"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Notification struct {
	ID         string                `json:"id"`
	UserID     string                `json:"userId"`
	Title      string                `json:"title"`
	Message    string                `json:"message"`
	Type       NullNotificationsType `json:"type"`
	IsRead     sql.NullBool          `json:"isRead"`
	EntityType sql.NullString        `json:"entityType"`
	EntityID   sql.NullString        `json:"entityId"`
	CreatedAt  sql.NullTime          `json:"createdAt"`
}

type SickLeafe struct {
	ID          string           `json:"id"`
	UserID      string           `json:"userId"`
	StartDate   time.Time        `json:"startDate"`
	EndDate     time.Time        `json:"endDate"`
	TotalDays   int32            `json:"totalDays"`
	Description sql.NullString   `json:"description"`
	CreatedAt   sql.NullTime     `json:"createdAt"`
	UpdatedAt   sql.NullTime     `json:"updatedAt"`
	Status      SickLeavesStatus `json:"status"`
}

type SystemSetting struct {
	ID           int32                         `json:"id"`
	SettingKey   string                        `json:"settingKey"`
	SettingValue sql.NullString                `json:"settingValue"`
	SettingType  NullSystemSettingsSettingType `json:"settingType"`
	Category     sql.NullString                `json:"category"`
	Description  sql.NullString                `json:"description"`
	IsPublic     sql.NullBool                  `json:"isPublic"`
	CreatedAt    sql.NullTime                  `json:"createdAt"`
	UpdatedAt    sql.NullTime                  `json:"updatedAt"`
}

type UserTimeEntry struct {
	ID          string       `json:"id"`
	UserID      string       `json:"userId"`
	EntryDate   time.Time    `json:"entryDate"`
	DayTypeID   string       `json:"dayTypeId"`
	HoursWorked string       `json:"hoursWorked"`
	CreatedAt   sql.NullTime `json:"createdAt"`
	UpdatedAt   sql.NullTime `json:"updatedAt"`
}

type Vacation struct {
	ID              string          `json:"id"`
	UserID          string          `json:"userId"`
	StartDate       time.Time       `json:"startDate"`
	EndDate         time.Time       `json:"endDate"`
	TotalDays       int32           `json:"totalDays"`
	Description     sql.NullString  `json:"description"`
	CreatedAt       sql.NullTime    `json:"createdAt"`
	UpdatedAt       sql.NullTime    `json:"updatedAt"`
	ManagerComment  sql.NullString  `json:"managerComment"`
	StatusUpdatedAt sql.NullTime    `json:"statusUpdatedAt"`
	Status          VacationsStatus `json:"status"`
	VacationTypeID  sql.NullString  `json:"vacationTypeId"`
}

type VacationType struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	SystemName     string    `json:"systemName"`
	ColorCode      string    `json:"colorCode"`
	AffectsBalance bool      `json:"affectsBalance"`
	IsActive       bool      `json:"isActive"`
	SortOrder      int32     `json:"sortOrder"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type WorkStandard struct {
	ID            string         `json:"id"`
	UserID        sql.NullString `json:"userId"`
	Month         int32          `json:"month"`
	Year          int32          `json:"year"`
	StandardHours int32          `json:"standardHours"`
	StandardDays  int32          `json:"standardDays"`
	Gender        int32          `json:"gender"`
	CreatedAt     sql.NullTime   `json:"createdAt"`
	UpdatedAt     sql.NullTime   `json:"updatedAt"`
}
