// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news_read_marks.sql

package repo

import (
	"context"
)

const getNewsReadMark = `-- name: GetNewsReadMark :one
SELECT
  user_id, last_seen_at
FROM
  news_read_marks
WHERE
  user_id = ?
`

func (q *Queries) GetNewsReadMark(ctx context.Context, userID string) (NewsReadMark, error) {
	row := q.db.QueryRowContext(ctx, getNewsReadMark, userID)
	var i NewsReadMark
	err := row.Scan(&i.UserID, &i.LastSeenAt)
	return i, err
}

const upsertNewsReadMark = `-- name: UpsertNewsReadMark :exec
INSERT INTO
  news_read_marks (user_id, last_seen_at)
VALUES
  (?, UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE
  last_seen_at = UTC_TIMESTAMP()
`

func (q *Queries) UpsertNewsReadMark(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, upsertNewsReadMark, userID)
	return err
}
