// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news_posts.sql

package repo

import (
	"context"
	"time"
)

const countNewsPostsSince = `-- name: CountNewsPostsSince :one
SELECT
  COUNT(*)
FROM
  news_posts
WHERE
  created_at > ?
`

func (q *Queries) CountNewsPostsSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewsPostsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNewsPost = `-- name: CreateNewsPost :exec
INSERT INTO
  news_posts (id, title, body, created_at, updated_at)
VALUES
  (?, ?, ?, UTC_TIMESTAMP(), UTC_TIMESTAMP())
`

type CreateNewsPostParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

func (q *Queries) CreateNewsPost(ctx context.Context, arg CreateNewsPostParams) error {
	_, err := q.db.ExecContext(ctx, createNewsPost, arg.ID, arg.Title, arg.Body)
	return err
}

const deleteNewsPost = `-- name: DeleteNewsPost :exec
DELETE FROM news_posts
WHERE
  id = ?
`

func (q *Queries) DeleteNewsPost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNewsPost, id)
	return err
}

const getNewsPostByID = `-- name: GetNewsPostByID :one
SELECT
  id, title, body, created_at, updated_at
FROM
  news_posts
WHERE
  id = ?
`

func (q *Queries) GetNewsPostByID(ctx context.Context, id string) (NewsPost, error) {
	row := q.db.QueryRowContext(ctx, getNewsPostByID, id)
	var i NewsPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNewsPosts = `-- name: ListNewsPosts :many
SELECT
  id, title, body, created_at, updated_at
FROM
  news_posts
ORDER BY
  created_at DESC
`

func (q *Queries) ListNewsPosts(ctx context.Context) ([]NewsPost, error) {
	rows, err := q.db.QueryContext(ctx, listNewsPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsPost
	for rows.Next() {
		var i NewsPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNewsPost = `-- name: UpdateNewsPost :exec
UPDATE news_posts
SET
  title = ?,
  body = ?,
  updated_at = UTC_TIMESTAMP()
WHERE
  id = ?
`

type UpdateNewsPostParams struct {
	Title string `json:"title"`
	Body  string `json:"body"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateNewsPost(ctx context.Context, arg UpdateNewsPostParams) error {
	_, err := q.db.ExecContext(ctx, updateNewsPost, arg.Title, arg.Body, arg.ID)
	return err
}
