// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_templates.sql

package repo

import (
	"context"
)

const createNotificationTemplate = `-- name: CreateNotificationTemplate :exec
INSERT INTO
  notification_templates (id, name, title, message, created_at, updated_at)
VALUES
  (?, ?, ?, ?, UTC_TIMESTAMP(), UTC_TIMESTAMP())
`

type CreateNotificationTemplateParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Title   string `json:"title"`
	Message string `json:"message"`
}

func (q *Queries) CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationTemplate,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Message,
	)
	return err
}

const deleteNotificationTemplate = `-- name: DeleteNotificationTemplate :exec
DELETE FROM notification_templates
WHERE
  id = ?
`

func (q *Queries) DeleteNotificationTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationTemplate, id)
	return err
}

const getNotificationTemplateByID = `-- name: GetNotificationTemplateByID :one
SELECT
  id, name, title, message, created_at, updated_at
FROM
  notification_templates
WHERE
  id = ?
`

func (q *Queries) GetNotificationTemplateByID(ctx context.Context, id string) (NotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, getNotificationTemplateByID, id)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationTemplateByName = `-- name: GetNotificationTemplateByName :one
SELECT
  id, name, title, message, created_at, updated_at
FROM
  notification_templates
WHERE
  name = ?
`

func (q *Queries) GetNotificationTemplateByName(ctx context.Context, name string) (NotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, getNotificationTemplateByName, name)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationTemplates = `-- name: ListNotificationTemplates :many
SELECT
  id, name, title, message, created_at, updated_at
FROM
  notification_templates
ORDER BY
  name
`

func (q *Queries) ListNotificationTemplates(ctx context.Context) ([]NotificationTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationTemplate
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationTemplate = `-- name: UpdateNotificationTemplate :exec
UPDATE notification_templates
SET
  name = ?,
  title = ?,
  message = ?,
  updated_at = UTC_TIMESTAMP()
WHERE
  id = ?
`

type UpdateNotificationTemplateParams struct {
	Name    string `json:"name"`
	Title   string `json:"title"`
	Message string `json:"message"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationTemplate,
		arg.Name,
		arg.Title,
		arg.Message,
		arg.ID,
	)
	return err
}
