// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repo

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT
  COUNT(*)
FROM
  notifications
WHERE
  user_id = ?
  AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO
  notifications (user_id, title, message, type, entity_type, entity_id)
VALUES
  (?, ?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	UserID     string                `json:"userId"`
	Title      string                `json:"title"`
	Message    string                `json:"message"`
	Type       NullNotificationsType `json:"type"`
	EntityType sql.NullString        `json:"entityType"`
	EntityID   sql.NullString        `json:"entityId"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT
  id, user_id, title, message, type, is_read, entity_type, entity_id, created_at
FROM
  notifications
WHERE
  user_id = ?
ORDER BY
  created_at DESC
LIMIT
  ?
OFFSET
  ?
`

type ListNotificationsByUserParams struct {
	UserID string `json:"userId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.IsRead,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET
  is_read = TRUE
WHERE
  user_id = ?
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET
  is_read = TRUE
WHERE
  id = ?
  AND user_id = ?
`

type MarkNotificationReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
