// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CreateCalendarEvents(ctx context.Context, arg CreateCalendarEventsParams) (sql.Result, error)
	CreateDayType(ctx context.Context, arg CreateDayTypeParams) error
	CreateUserTimeEntry(ctx context.Context, arg CreateUserTimeEntryParams) error
	CreateWorkStandard(ctx context.Context, arg CreateWorkStandardParams) error
	DeleteCalendarEvents(ctx context.Context, id string) error
	DeleteDayType(ctx context.Context, id string) error
	DeleteUserTimeEntries(ctx context.Context, arg DeleteUserTimeEntriesParams) error
	DeleteUserTimeEntry(ctx context.Context, arg DeleteUserTimeEntryParams) error
	DeleteWorkStandard(ctx context.Context, id string) error
	GetCalendarEventsByDate(ctx context.Context, eventDate time.Time) (GetCalendarEventsByDateRow, error)
	GetCalendarEventsById(ctx context.Context, id string) (GetCalendarEventsByIdRow, error)
	// ============================================
	// calendar_events queries
	// ============================================
	GetCalendarEventsForMonth(ctx context.Context, arg GetCalendarEventsForMonthParams) ([]GetCalendarEventsForMonthRow, error)
	GetCalendarEventsForYear(ctx context.Context, year time.Time) ([]GetCalendarEventsForYearRow, error)
	GetDayTypeByID(ctx context.Context, id string) (DayType, error)
	// ============================================
	// day_types queries
	// ============================================
	GetDayTypes(ctx context.Context) ([]DayType, error)
	GetTotalDaysByMonthWithSystemName(ctx context.Context, arg GetTotalDaysByMonthWithSystemNameParams) (int64, error)
	GetTotalDaysByYearWithSystemName(ctx context.Context, arg GetTotalDaysByYearWithSystemNameParams) (int64, error)
	GetTotalHoursByMonth(ctx context.Context, arg GetTotalHoursByMonthParams) (interface{}, error)
	GetTotalHoursByYear(ctx context.Context, arg GetTotalHoursByYearParams) (interface{}, error)
	// ============================================
	// user_time_entries queries
	// ============================================
	GetUserTimeEntriesForMonth(ctx context.Context, arg GetUserTimeEntriesForMonthParams) ([]UserTimeEntry, error)
	GetUserTimeEntryById(ctx context.Context, id string) (UserTimeEntry, error)
	GetUserTimeEntryByIds(ctx context.Context, ids []string) ([]UserTimeEntry, error)
	GetWorkDaysByMonth(ctx context.Context, arg GetWorkDaysByMonthParams) (int64, error)
	// ============================================
	// work_standards queries
	// ============================================
	GetWorkStandardsById(ctx context.Context, id string) (WorkStandard, error)
	GetWorkStandardsByMonth(ctx context.Context, arg GetWorkStandardsByMonthParams) ([]WorkStandard, error)
	GetWorkStandardsByMonthAndGenderId(ctx context.Context, arg GetWorkStandardsByMonthAndGenderIdParams) (WorkStandard, error)
	GetWorkStandardsByYear(ctx context.Context, year int32) ([]WorkStandard, error)
	UpdateAffectsVacationDayType(ctx context.Context, arg UpdateAffectsVacationDayTypeParams) error
	UpdateCalendarEvents(ctx context.Context, arg UpdateCalendarEventsParams) error
	UpdateColorCodeDayType(ctx context.Context, arg UpdateColorCodeDayTypeParams) error
	UpdateDayType(ctx context.Context, arg UpdateDayTypeParams) error
	UpdateIsUserSelectDayType(ctx context.Context, arg UpdateIsUserSelectDayTypeParams) error
	UpdateIsWorkDayType(ctx context.Context, arg UpdateIsWorkDayTypeParams) error
	UpdateNameDayType(ctx context.Context, arg UpdateNameDayTypeParams) error
	UpdateSystemNameDayType(ctx context.Context, arg UpdateSystemNameDayTypeParams) error
	UpdateUserTimeEntries(ctx context.Context, arg UpdateUserTimeEntriesParams) error
	UpdateUserTimeEntry(ctx context.Context, arg UpdateUserTimeEntryParams) error
	UpdateWorkStandard(ctx context.Context, arg UpdateWorkStandardParams) error
}

var _ Querier = (*Queries)(nil)
