// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AssignVacationType(ctx context.Context, arg AssignVacationTypeParams) error
	CountFileCategoryChildren(ctx context.Context, parentID sql.NullString) (int64, error)
	CountFilesInCategory(ctx context.Context, categoryID sql.NullString) (int64, error)
	CountVacationsByType(ctx context.Context, vacationTypeID sql.NullString) (int64, error)
	CreateCalendarEvents(ctx context.Context, arg CreateCalendarEventsParams) (sql.Result, error)
	CreateDayType(ctx context.Context, arg CreateDayTypeParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) error
	CreateFileCategory(ctx context.Context, arg CreateFileCategoryParams) error
	CreateFileEntityRef(ctx context.Context, arg CreateFileEntityRefParams) error
	CreateSickLeave(ctx context.Context, arg CreateSickLeaveParams) error
	CreateSystemSetting(ctx context.Context, arg CreateSystemSettingParams) error
	CreateUserTimeEntry(ctx context.Context, arg CreateUserTimeEntryParams) error
	CreateVacation(ctx context.Context, arg CreateVacationParams) error
	CreateVacationType(ctx context.Context, arg CreateVacationTypeParams) error
	CreateWorkStandard(ctx context.Context, arg CreateWorkStandardParams) error
	DeleteAllFileEntityRefsByFile(ctx context.Context, fileID string) error
	DeleteCalendarEvents(ctx context.Context, id string) error
	DeleteDayType(ctx context.Context, id string) error
	DeleteFileCategory(ctx context.Context, id string) error
	DeleteSickLeave(ctx context.Context, id string) error
	DeleteSystemSetting(ctx context.Context, settingKey string) error
	DeleteUserTimeEntries(ctx context.Context, arg DeleteUserTimeEntriesParams) error
	DeleteUserTimeEntry(ctx context.Context, arg DeleteUserTimeEntryParams) error
	DeleteVacation(ctx context.Context, id string) error
	DeleteVacationType(ctx context.Context, id string) error
	DeleteWorkStandard(ctx context.Context, id string) error
	GetActiveVacationTypes(ctx context.Context) ([]VacationType, error)
	GetAllUsersSickLeavesByYear(ctx context.Context, arg GetAllUsersSickLeavesByYearParams) ([]GetAllUsersSickLeavesByYearRow, error)
	GetAllUsersVacationsByYear(ctx context.Context, arg GetAllUsersVacationsByYearParams) ([]GetAllUsersVacationsByYearRow, error)
	GetCalendarEventsByDate(ctx context.Context, eventDate time.Time) (GetCalendarEventsByDateRow, error)
	GetCalendarEventsById(ctx context.Context, id string) (GetCalendarEventsByIdRow, error)
	// ============================================
	// calendar_events queries
	// ============================================
	GetCalendarEventsForMonth(ctx context.Context, arg GetCalendarEventsForMonthParams) ([]GetCalendarEventsForMonthRow, error)
	GetCalendarEventsForYear(ctx context.Context, year time.Time) ([]GetCalendarEventsForYearRow, error)
	GetCountSickLeavesByStatus(ctx context.Context, arg GetCountSickLeavesByStatusParams) (interface{}, error)
	GetCountVacationsByStatus(ctx context.Context, arg GetCountVacationsByStatusParams) (interface{}, error)
	GetDayTypeByID(ctx context.Context, id string) (DayType, error)
	GetDayTypeBySystemName(ctx context.Context, systemName string) (DayType, error)
	// ============================================
	// day_types queries
	// ============================================
	GetDayTypes(ctx context.Context) ([]DayType, error)
	GetFileByID(ctx context.Context, id string) (GetFileByIDRow, error)
	// ============================================
	// file_categories queries
	// ============================================
	GetFileCategories(ctx context.Context) ([]FileCategory, error)
	GetFileCategoryByID(ctx context.Context, id string) (FileCategory, error)
	GetFileCategoryByParentAndName(ctx context.Context, arg GetFileCategoryByParentAndNameParams) (FileCategory, error)
	GetFileCategoryBySystemName(ctx context.Context, systemName sql.NullString) (FileCategory, error)
	GetMonthlyStatistics(ctx context.Context, arg GetMonthlyStatisticsParams) (GetMonthlyStatisticsRow, error)
	GetPublicSystemSettings(ctx context.Context) ([]SystemSetting, error)
	GetSickLeaveByID(ctx context.Context, id string) (GetSickLeaveByIDRow, error)
	GetSickLeavesByYear(ctx context.Context, arg GetSickLeavesByYearParams) ([]GetSickLeavesByYearRow, error)
	GetSystemSettingByKey(ctx context.Context, settingKey string) (SystemSetting, error)
	GetSystemSettingByKeyAndCategory(ctx context.Context, arg GetSystemSettingByKeyAndCategoryParams) (SystemSetting, error)
	// ============================================
	// system_settings queries
	// ============================================
	GetSystemSettings(ctx context.Context) ([]SystemSetting, error)
	GetSystemSettingsByCategory(ctx context.Context, category sql.NullString) ([]SystemSetting, error)
	GetTotalDaysByMonthWithSystemName(ctx context.Context, arg GetTotalDaysByMonthWithSystemNameParams) (interface{}, error)
	GetTotalDaysByYearWithSystemName(ctx context.Context, arg GetTotalDaysByYearWithSystemNameParams) (interface{}, error)
	GetTotalHoursByMonth(ctx context.Context, arg GetTotalHoursByMonthParams) (interface{}, error)
	GetTotalHoursByYear(ctx context.Context, arg GetTotalHoursByYearParams) (interface{}, error)
	// ============================================
	// user_time_entries queries
	// ============================================
	GetUserTimeEntriesForMonth(ctx context.Context, arg GetUserTimeEntriesForMonthParams) ([]UserTimeEntry, error)
	GetUserTimeEntryById(ctx context.Context, id string) (UserTimeEntry, error)
	GetUserTimeEntryByIds(ctx context.Context, ids []string) ([]UserTimeEntry, error)
	GetVacationByID(ctx context.Context, id string) (GetVacationByIDRow, error)
	GetVacationDaysByMonth(ctx context.Context, arg GetVacationDaysByMonthParams) (interface{}, error)
	GetVacationDaysByYear(ctx context.Context, arg GetVacationDaysByYearParams) (interface{}, error)
	GetVacationTypeByID(ctx context.Context, id string) (VacationType, error)
	GetVacationTypeBySystemName(ctx context.Context, systemName string) (VacationType, error)
	// ============================================
	// vacation_types queries
	// ============================================
	GetVacationTypes(ctx context.Context) ([]VacationType, error)
	GetVacationsByYear(ctx context.Context, arg GetVacationsByYearParams) ([]GetVacationsByYearRow, error)
	GetWorkDaysByMonth(ctx context.Context, arg GetWorkDaysByMonthParams) (interface{}, error)
	// ============================================
	// work_standards queries
	// ============================================
	GetWorkStandardsById(ctx context.Context, id string) (WorkStandard, error)
	GetWorkStandardsByMonth(ctx context.Context, arg GetWorkStandardsByMonthParams) ([]WorkStandard, error)
	GetWorkStandardsByMonthAndGenderId(ctx context.Context, arg GetWorkStandardsByMonthAndGenderIdParams) (WorkStandard, error)
	GetWorkStandardsByMonthAndGenderIdAndUserId(ctx context.Context, arg GetWorkStandardsByMonthAndGenderIdAndUserIdParams) (WorkStandard, error)
	GetWorkStandardsByYear(ctx context.Context, year int32) ([]WorkStandard, error)
	HardDeleteFile(ctx context.Context, id string) error
	ListFilesByCategory(ctx context.Context, categoryID sql.NullString) ([]ListFilesByCategoryRow, error)
	ListFilesByEntity(ctx context.Context, arg ListFilesByEntityParams) ([]ListFilesByEntityRow, error)
	ListFilesByEntityType(ctx context.Context, entityType string) ([]ListFilesByEntityTypeRow, error)
	ListFilesByUploader(ctx context.Context, uploadedByUserID string) ([]ListFilesByUploaderRow, error)
	SoftDeleteFile(ctx context.Context, id string) error
	UpdateAffectsVacationDayType(ctx context.Context, arg UpdateAffectsVacationDayTypeParams) error
	UpdateCalendarEvents(ctx context.Context, arg UpdateCalendarEventsParams) error
	UpdateColorCodeDayType(ctx context.Context, arg UpdateColorCodeDayTypeParams) error
	UpdateDayType(ctx context.Context, arg UpdateDayTypeParams) error
	UpdateFileCategory(ctx context.Context, arg UpdateFileCategoryParams) error
	UpdateFileCategoryAssignment(ctx context.Context, arg UpdateFileCategoryAssignmentParams) error
	UpdateIsUserSelectDayType(ctx context.Context, arg UpdateIsUserSelectDayTypeParams) error
	UpdateIsWorkDayType(ctx context.Context, arg UpdateIsWorkDayTypeParams) error
	UpdateNameDayType(ctx context.Context, arg UpdateNameDayTypeParams) error
	UpdateSickLeaveStatus(ctx context.Context, arg UpdateSickLeaveStatusParams) error
	UpdateSystemNameDayType(ctx context.Context, arg UpdateSystemNameDayTypeParams) error
	UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) error
	UpdateUserTimeEntries(ctx context.Context, arg UpdateUserTimeEntriesParams) error
	UpdateUserTimeEntry(ctx context.Context, arg UpdateUserTimeEntryParams) error
	UpdateVacationStatus(ctx context.Context, arg UpdateVacationStatusParams) error
	UpdateVacationType(ctx context.Context, arg UpdateVacationTypeParams) error
	UpdateValueSystemSetting(ctx context.Context, arg UpdateValueSystemSettingParams) error
	UpdateWorkStandard(ctx context.Context, arg UpdateWorkStandardParams) error
}

var _ Querier = (*Queries)(nil)
