// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createReceipt = `-- name: CreateReceipt :exec

INSERT INTO
  receipts (
    id,
    user_id,
    fiscal_drive_number,
    fiscal_document_number,
    fiscal_sign,
    ticket_date,
    total_sum,
    seller_inn,
    seller_name,
    operation_type,
    has_paper,
    categories_manual,
    object_id,
    retail_place_address,
    request_number,
    cash_total_sum,
    ecash_total_sum,
    taxation_type,
    shift_number,
    kkt_reg_id,
    fiscal_document_format_ver,
    machine_number,
    retail_place,
    operator,
    prepaid_sum,
    nds20,
    nds10,
    nds0,
    nds_no,
    nds22,
    raw_qr,
    created_at,
    updated_at
  )
VALUES
  -- created_at/updated_at приходят из Go (time.Now().UTC()), а не
  -- UTC_TIMESTAMP() — та отдаёт только целые секунды (DATETIME(6) без долей
  -- секунды в значении бесполезен), а sqlc к тому же не знает сигнатуру
  -- UTC_TIMESTAMP(6) с аргументом (см. 023_receipts_timestamp_precision.sql).
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReceiptParams struct {
	ID                      string         `json:"id"`
	UserID                  string         `json:"userId"`
	FiscalDriveNumber       sql.NullString `json:"fiscalDriveNumber"`
	FiscalDocumentNumber    sql.NullString `json:"fiscalDocumentNumber"`
	FiscalSign              sql.NullString `json:"fiscalSign"`
	TicketDate              time.Time      `json:"ticketDate"`
	TotalSum                int64          `json:"totalSum"`
	SellerInn               sql.NullString `json:"sellerInn"`
	SellerName              sql.NullString `json:"sellerName"`
	OperationType           int32          `json:"operationType"`
	HasPaper                bool           `json:"hasPaper"`
	CategoriesManual        bool           `json:"categoriesManual"`
	ObjectID                sql.NullString `json:"objectId"`
	RetailPlaceAddress      sql.NullString `json:"retailPlaceAddress"`
	RequestNumber           sql.NullString `json:"requestNumber"`
	CashTotalSum            sql.NullInt64  `json:"cashTotalSum"`
	EcashTotalSum           sql.NullInt64  `json:"ecashTotalSum"`
	TaxationType            sql.NullInt32  `json:"taxationType"`
	ShiftNumber             sql.NullInt32  `json:"shiftNumber"`
	KktRegID                sql.NullString `json:"kktRegId"`
	FiscalDocumentFormatVer sql.NullInt32  `json:"fiscalDocumentFormatVer"`
	MachineNumber           sql.NullString `json:"machineNumber"`
	RetailPlace             sql.NullString `json:"retailPlace"`
	Operator                sql.NullString `json:"operator"`
	PrepaidSum              sql.NullInt64  `json:"prepaidSum"`
	Nds20                   int64          `json:"nds20"`
	Nds10                   int64          `json:"nds10"`
	Nds0                    int64          `json:"nds0"`
	NdsNo                   int64          `json:"ndsNo"`
	Nds22                   int64          `json:"nds22"`
	RawQr                   sql.NullString `json:"rawQr"`
	CreatedAt               time.Time      `json:"createdAt"`
	UpdatedAt               time.Time      `json:"updatedAt"`
}

// ============================================
// receipts / receipt_items queries
// ============================================
func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) error {
	_, err := q.db.ExecContext(ctx, createReceipt,
		arg.ID,
		arg.UserID,
		arg.FiscalDriveNumber,
		arg.FiscalDocumentNumber,
		arg.FiscalSign,
		arg.TicketDate,
		arg.TotalSum,
		arg.SellerInn,
		arg.SellerName,
		arg.OperationType,
		arg.HasPaper,
		arg.CategoriesManual,
		arg.ObjectID,
		arg.RetailPlaceAddress,
		arg.RequestNumber,
		arg.CashTotalSum,
		arg.EcashTotalSum,
		arg.TaxationType,
		arg.ShiftNumber,
		arg.KktRegID,
		arg.FiscalDocumentFormatVer,
		arg.MachineNumber,
		arg.RetailPlace,
		arg.Operator,
		arg.PrepaidSum,
		arg.Nds20,
		arg.Nds10,
		arg.Nds0,
		arg.NdsNo,
		arg.Nds22,
		arg.RawQr,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createReceiptItem = `-- name: CreateReceiptItem :exec
INSERT INTO
  receipt_items (receipt_id, position_no, name, price, quantity, sum, nds_code)
VALUES
  (?, ?, ?, ?, ?, ?, ?)
`

type CreateReceiptItemParams struct {
	ReceiptID  string        `json:"receiptId"`
	PositionNo sql.NullInt32 `json:"positionNo"`
	Name       string        `json:"name"`
	Price      int64         `json:"price"`
	Quantity   string        `json:"quantity"`
	Sum        int64         `json:"sum"`
	NdsCode    sql.NullInt32 `json:"ndsCode"`
}

func (q *Queries) CreateReceiptItem(ctx context.Context, arg CreateReceiptItemParams) error {
	_, err := q.db.ExecContext(ctx, createReceiptItem,
		arg.ReceiptID,
		arg.PositionNo,
		arg.Name,
		arg.Price,
		arg.Quantity,
		arg.Sum,
		arg.NdsCode,
	)
	return err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipts
WHERE
  id = ?
`

func (q *Queries) DeleteReceipt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReceipt, id)
	return err
}

const getReceiptByFiscalKey = `-- name: GetReceiptByFiscalKey :one
SELECT
  id, user_id, ticket_date, total_sum, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at, shift_number, kkt_reg_id, fiscal_document_format_ver, machine_number, retail_place, operator, prepaid_sum, nds22, has_paper, fiscal_drive_number, fiscal_document_number, fiscal_sign, seller_inn, object_id, categories_manual
FROM
  receipts
WHERE
  fiscal_drive_number = ?
  AND fiscal_document_number = ?
  AND fiscal_sign = ?
`

type GetReceiptByFiscalKeyParams struct {
	FiscalDriveNumber    sql.NullString `json:"fiscalDriveNumber"`
	FiscalDocumentNumber sql.NullString `json:"fiscalDocumentNumber"`
	FiscalSign           sql.NullString `json:"fiscalSign"`
}

func (q *Queries) GetReceiptByFiscalKey(ctx context.Context, arg GetReceiptByFiscalKeyParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptByFiscalKey, arg.FiscalDriveNumber, arg.FiscalDocumentNumber, arg.FiscalSign)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TicketDate,
		&i.TotalSum,
		&i.SellerName,
		&i.OperationType,
		&i.RetailPlaceAddress,
		&i.RequestNumber,
		&i.CashTotalSum,
		&i.EcashTotalSum,
		&i.TaxationType,
		&i.Nds20,
		&i.Nds10,
		&i.Nds0,
		&i.NdsNo,
		&i.RawQr,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShiftNumber,
		&i.KktRegID,
		&i.FiscalDocumentFormatVer,
		&i.MachineNumber,
		&i.RetailPlace,
		&i.Operator,
		&i.PrepaidSum,
		&i.Nds22,
		&i.HasPaper,
		&i.FiscalDriveNumber,
		&i.FiscalDocumentNumber,
		&i.FiscalSign,
		&i.SellerInn,
		&i.ObjectID,
		&i.CategoriesManual,
	)
	return i, err
}

const getReceiptByID = `-- name: GetReceiptByID :one
SELECT
  id, user_id, ticket_date, total_sum, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at, shift_number, kkt_reg_id, fiscal_document_format_ver, machine_number, retail_place, operator, prepaid_sum, nds22, has_paper, fiscal_drive_number, fiscal_document_number, fiscal_sign, seller_inn, object_id, categories_manual
FROM
  receipts
WHERE
  id = ?
`

func (q *Queries) GetReceiptByID(ctx context.Context, id string) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptByID, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TicketDate,
		&i.TotalSum,
		&i.SellerName,
		&i.OperationType,
		&i.RetailPlaceAddress,
		&i.RequestNumber,
		&i.CashTotalSum,
		&i.EcashTotalSum,
		&i.TaxationType,
		&i.Nds20,
		&i.Nds10,
		&i.Nds0,
		&i.NdsNo,
		&i.RawQr,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShiftNumber,
		&i.KktRegID,
		&i.FiscalDocumentFormatVer,
		&i.MachineNumber,
		&i.RetailPlace,
		&i.Operator,
		&i.PrepaidSum,
		&i.Nds22,
		&i.HasPaper,
		&i.FiscalDriveNumber,
		&i.FiscalDocumentNumber,
		&i.FiscalSign,
		&i.SellerInn,
		&i.ObjectID,
		&i.CategoriesManual,
	)
	return i, err
}

const listAllReceipts = `-- name: ListAllReceipts :many
SELECT
  id, user_id, ticket_date, total_sum, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at, shift_number, kkt_reg_id, fiscal_document_format_ver, machine_number, retail_place, operator, prepaid_sum, nds22, has_paper, fiscal_drive_number, fiscal_document_number, fiscal_sign, seller_inn, object_id, categories_manual
FROM
  receipts
ORDER BY
  ticket_date DESC
`

func (q *Queries) ListAllReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listAllReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TicketDate,
			&i.TotalSum,
			&i.SellerName,
			&i.OperationType,
			&i.RetailPlaceAddress,
			&i.RequestNumber,
			&i.CashTotalSum,
			&i.EcashTotalSum,
			&i.TaxationType,
			&i.Nds20,
			&i.Nds10,
			&i.Nds0,
			&i.NdsNo,
			&i.RawQr,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShiftNumber,
			&i.KktRegID,
			&i.FiscalDocumentFormatVer,
			&i.MachineNumber,
			&i.RetailPlace,
			&i.Operator,
			&i.PrepaidSum,
			&i.Nds22,
			&i.HasPaper,
			&i.FiscalDriveNumber,
			&i.FiscalDocumentNumber,
			&i.FiscalSign,
			&i.SellerInn,
			&i.ObjectID,
			&i.CategoriesManual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptItemsByReceipt = `-- name: ListReceiptItemsByReceipt :many
SELECT
  id, receipt_id, position_no, name, price, quantity, sum, nds_code
FROM
  receipt_items
WHERE
  receipt_id = ?
ORDER BY
  position_no,
  id
`

func (q *Queries) ListReceiptItemsByReceipt(ctx context.Context, receiptID string) ([]ReceiptItem, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptItemsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptItem
	for rows.Next() {
		var i ReceiptItem
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.PositionNo,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.Sum,
			&i.NdsCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByUser = `-- name: ListReceiptsByUser :many
SELECT
  id, user_id, ticket_date, total_sum, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at, shift_number, kkt_reg_id, fiscal_document_format_ver, machine_number, retail_place, operator, prepaid_sum, nds22, has_paper, fiscal_drive_number, fiscal_document_number, fiscal_sign, seller_inn, object_id, categories_manual
FROM
  receipts
WHERE
  user_id = ?
ORDER BY
  ticket_date DESC
`

func (q *Queries) ListReceiptsByUser(ctx context.Context, userID string) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TicketDate,
			&i.TotalSum,
			&i.SellerName,
			&i.OperationType,
			&i.RetailPlaceAddress,
			&i.RequestNumber,
			&i.CashTotalSum,
			&i.EcashTotalSum,
			&i.TaxationType,
			&i.Nds20,
			&i.Nds10,
			&i.Nds0,
			&i.NdsNo,
			&i.RawQr,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShiftNumber,
			&i.KktRegID,
			&i.FiscalDocumentFormatVer,
			&i.MachineNumber,
			&i.RetailPlace,
			&i.Operator,
			&i.PrepaidSum,
			&i.Nds22,
			&i.HasPaper,
			&i.FiscalDriveNumber,
			&i.FiscalDocumentNumber,
			&i.FiscalSign,
			&i.SellerInn,
			&i.ObjectID,
			&i.CategoriesManual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReceiptObjectID = `-- name: UpdateReceiptObjectID :exec
UPDATE receipts
SET
  object_id = ?,
  updated_at = ?
WHERE
  id = ?
`

type UpdateReceiptObjectIDParams struct {
	ObjectID  sql.NullString `json:"objectId"`
	UpdatedAt time.Time      `json:"updatedAt"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateReceiptObjectID(ctx context.Context, arg UpdateReceiptObjectIDParams) error {
	_, err := q.db.ExecContext(ctx, updateReceiptObjectID, arg.ObjectID, arg.UpdatedAt, arg.ID)
	return err
}

const updateReceiptOwner = `-- name: UpdateReceiptOwner :exec
UPDATE receipts
SET
  user_id = ?,
  updated_at = ?
WHERE
  id = ?
`

type UpdateReceiptOwnerParams struct {
	UserID    string    `json:"userId"`
	UpdatedAt time.Time `json:"updatedAt"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateReceiptOwner(ctx context.Context, arg UpdateReceiptOwnerParams) error {
	_, err := q.db.ExecContext(ctx, updateReceiptOwner, arg.UserID, arg.UpdatedAt, arg.ID)
	return err
}
