// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createReceipt = `-- name: CreateReceipt :exec

INSERT INTO
  receipts (
    id,
    user_id,
    fiscal_drive_number,
    fiscal_document_number,
    fiscal_sign,
    ticket_date,
    total_sum,
    seller_inn,
    seller_name,
    operation_type,
    retail_place_address,
    request_number,
    cash_total_sum,
    ecash_total_sum,
    taxation_type,
    nds20,
    nds10,
    nds0,
    nds_no,
    raw_qr,
    created_at,
    updated_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, UTC_TIMESTAMP(), UTC_TIMESTAMP())
`

type CreateReceiptParams struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"userId"`
	FiscalDriveNumber    string         `json:"fiscalDriveNumber"`
	FiscalDocumentNumber string         `json:"fiscalDocumentNumber"`
	FiscalSign           string         `json:"fiscalSign"`
	TicketDate           time.Time      `json:"ticketDate"`
	TotalSum             int64          `json:"totalSum"`
	SellerInn            string         `json:"sellerInn"`
	SellerName           sql.NullString `json:"sellerName"`
	OperationType        int32          `json:"operationType"`
	RetailPlaceAddress   sql.NullString `json:"retailPlaceAddress"`
	RequestNumber        sql.NullString `json:"requestNumber"`
	CashTotalSum         sql.NullInt64  `json:"cashTotalSum"`
	EcashTotalSum        sql.NullInt64  `json:"ecashTotalSum"`
	TaxationType         sql.NullInt32  `json:"taxationType"`
	Nds20                int64          `json:"nds20"`
	Nds10                int64          `json:"nds10"`
	Nds0                 int64          `json:"nds0"`
	NdsNo                int64          `json:"ndsNo"`
	RawQr                sql.NullString `json:"rawQr"`
}

// ============================================
// receipts / receipt_items queries
// ============================================
func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) error {
	_, err := q.db.ExecContext(ctx, createReceipt,
		arg.ID,
		arg.UserID,
		arg.FiscalDriveNumber,
		arg.FiscalDocumentNumber,
		arg.FiscalSign,
		arg.TicketDate,
		arg.TotalSum,
		arg.SellerInn,
		arg.SellerName,
		arg.OperationType,
		arg.RetailPlaceAddress,
		arg.RequestNumber,
		arg.CashTotalSum,
		arg.EcashTotalSum,
		arg.TaxationType,
		arg.Nds20,
		arg.Nds10,
		arg.Nds0,
		arg.NdsNo,
		arg.RawQr,
	)
	return err
}

const createReceiptItem = `-- name: CreateReceiptItem :exec
INSERT INTO
  receipt_items (receipt_id, position_no, name, price, quantity, sum)
VALUES
  (?, ?, ?, ?, ?, ?)
`

type CreateReceiptItemParams struct {
	ReceiptID  string        `json:"receiptId"`
	PositionNo sql.NullInt32 `json:"positionNo"`
	Name       string        `json:"name"`
	Price      int64         `json:"price"`
	Quantity   string        `json:"quantity"`
	Sum        int64         `json:"sum"`
}

func (q *Queries) CreateReceiptItem(ctx context.Context, arg CreateReceiptItemParams) error {
	_, err := q.db.ExecContext(ctx, createReceiptItem,
		arg.ReceiptID,
		arg.PositionNo,
		arg.Name,
		arg.Price,
		arg.Quantity,
		arg.Sum,
	)
	return err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipts
WHERE
  id = ?
`

func (q *Queries) DeleteReceipt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReceipt, id)
	return err
}

const getReceiptByFiscalKey = `-- name: GetReceiptByFiscalKey :one
SELECT
  id, user_id, fiscal_drive_number, fiscal_document_number, fiscal_sign, ticket_date, total_sum, seller_inn, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at
FROM
  receipts
WHERE
  fiscal_drive_number = ?
  AND fiscal_document_number = ?
  AND fiscal_sign = ?
`

type GetReceiptByFiscalKeyParams struct {
	FiscalDriveNumber    string `json:"fiscalDriveNumber"`
	FiscalDocumentNumber string `json:"fiscalDocumentNumber"`
	FiscalSign           string `json:"fiscalSign"`
}

func (q *Queries) GetReceiptByFiscalKey(ctx context.Context, arg GetReceiptByFiscalKeyParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptByFiscalKey, arg.FiscalDriveNumber, arg.FiscalDocumentNumber, arg.FiscalSign)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FiscalDriveNumber,
		&i.FiscalDocumentNumber,
		&i.FiscalSign,
		&i.TicketDate,
		&i.TotalSum,
		&i.SellerInn,
		&i.SellerName,
		&i.OperationType,
		&i.RetailPlaceAddress,
		&i.RequestNumber,
		&i.CashTotalSum,
		&i.EcashTotalSum,
		&i.TaxationType,
		&i.Nds20,
		&i.Nds10,
		&i.Nds0,
		&i.NdsNo,
		&i.RawQr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceiptByID = `-- name: GetReceiptByID :one
SELECT
  id, user_id, fiscal_drive_number, fiscal_document_number, fiscal_sign, ticket_date, total_sum, seller_inn, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at
FROM
  receipts
WHERE
  id = ?
`

func (q *Queries) GetReceiptByID(ctx context.Context, id string) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptByID, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FiscalDriveNumber,
		&i.FiscalDocumentNumber,
		&i.FiscalSign,
		&i.TicketDate,
		&i.TotalSum,
		&i.SellerInn,
		&i.SellerName,
		&i.OperationType,
		&i.RetailPlaceAddress,
		&i.RequestNumber,
		&i.CashTotalSum,
		&i.EcashTotalSum,
		&i.TaxationType,
		&i.Nds20,
		&i.Nds10,
		&i.Nds0,
		&i.NdsNo,
		&i.RawQr,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReceipts = `-- name: ListAllReceipts :many
SELECT
  id, user_id, fiscal_drive_number, fiscal_document_number, fiscal_sign, ticket_date, total_sum, seller_inn, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at
FROM
  receipts
ORDER BY
  ticket_date DESC
`

func (q *Queries) ListAllReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listAllReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FiscalDriveNumber,
			&i.FiscalDocumentNumber,
			&i.FiscalSign,
			&i.TicketDate,
			&i.TotalSum,
			&i.SellerInn,
			&i.SellerName,
			&i.OperationType,
			&i.RetailPlaceAddress,
			&i.RequestNumber,
			&i.CashTotalSum,
			&i.EcashTotalSum,
			&i.TaxationType,
			&i.Nds20,
			&i.Nds10,
			&i.Nds0,
			&i.NdsNo,
			&i.RawQr,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptItemsByReceipt = `-- name: ListReceiptItemsByReceipt :many
SELECT
  id, receipt_id, position_no, name, price, quantity, sum
FROM
  receipt_items
WHERE
  receipt_id = ?
ORDER BY
  position_no,
  id
`

func (q *Queries) ListReceiptItemsByReceipt(ctx context.Context, receiptID string) ([]ReceiptItem, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptItemsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptItem
	for rows.Next() {
		var i ReceiptItem
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.PositionNo,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.Sum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByUser = `-- name: ListReceiptsByUser :many
SELECT
  id, user_id, fiscal_drive_number, fiscal_document_number, fiscal_sign, ticket_date, total_sum, seller_inn, seller_name, operation_type, retail_place_address, request_number, cash_total_sum, ecash_total_sum, taxation_type, nds20, nds10, nds0, nds_no, raw_qr, created_at, updated_at
FROM
  receipts
WHERE
  user_id = ?
ORDER BY
  ticket_date DESC
`

func (q *Queries) ListReceiptsByUser(ctx context.Context, userID string) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FiscalDriveNumber,
			&i.FiscalDocumentNumber,
			&i.FiscalSign,
			&i.TicketDate,
			&i.TotalSum,
			&i.SellerInn,
			&i.SellerName,
			&i.OperationType,
			&i.RetailPlaceAddress,
			&i.RequestNumber,
			&i.CashTotalSum,
			&i.EcashTotalSum,
			&i.TaxationType,
			&i.Nds20,
			&i.Nds10,
			&i.Nds0,
			&i.NdsNo,
			&i.RawQr,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
