// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt_categories.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createCategory = `-- name: CreateCategory :execlastid
INSERT INTO
  categories (name, is_system)
VALUES
  (?, 0)
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategory, name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createKeyword = `-- name: CreateKeyword :exec
INSERT INTO
  keyword_category (keyword, category_id, is_system)
VALUES
  (?, ?, 0)
`

type CreateKeywordParams struct {
	Keyword    string `json:"keyword"`
	CategoryID int32  `json:"categoryId"`
}

func (q *Queries) CreateKeyword(ctx context.Context, arg CreateKeywordParams) error {
	_, err := q.db.ExecContext(ctx, createKeyword, arg.Keyword, arg.CategoryID)
	return err
}

const deleteAutoCategoryLinksBySellerInn = `-- name: DeleteAutoCategoryLinksBySellerInn :exec
DELETE FROM receipt_categories
WHERE
  receipt_id IN (
    SELECT
      id
    FROM
      receipts
    WHERE
      seller_inn = ?
      AND categories_manual = FALSE
  )
`

// Ретроактивное обновление по продавцу (см. receiptcategory.Service.
// UpdateMerchant) — только чеки, где категории не выбраны вручную.
func (q *Queries) DeleteAutoCategoryLinksBySellerInn(ctx context.Context, sellerInn sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteAutoCategoryLinksBySellerInn, sellerInn)
	return err
}

const deleteReceiptCategoryLinks = `-- name: DeleteReceiptCategoryLinks :exec
DELETE FROM receipt_categories
WHERE
  receipt_id = ?
`

func (q *Queries) DeleteReceiptCategoryLinks(ctx context.Context, receiptID string) error {
	_, err := q.db.ExecContext(ctx, deleteReceiptCategoryLinks, receiptID)
	return err
}

const getMerchantCategory = `-- name: GetMerchantCategory :one
SELECT
  inn, category_id, source
FROM
  merchant_category
WHERE
  inn = ?
`

func (q *Queries) GetMerchantCategory(ctx context.Context, inn string) (MerchantCategory, error) {
	row := q.db.QueryRowContext(ctx, getMerchantCategory, inn)
	var i MerchantCategory
	err := row.Scan(&i.Inn, &i.CategoryID, &i.Source)
	return i, err
}

const insertAutoCategoryLinkBySellerInn = `-- name: InsertAutoCategoryLinkBySellerInn :execrows
INSERT IGNORE INTO
  receipt_categories (receipt_id, category_id)
SELECT
  id,
  ?
FROM
  receipts
WHERE
  seller_inn = ?
  AND categories_manual = FALSE
`

type InsertAutoCategoryLinkBySellerInnParams struct {
	CategoryID int32          `json:"categoryId"`
	SellerInn  sql.NullString `json:"sellerInn"`
}

func (q *Queries) InsertAutoCategoryLinkBySellerInn(ctx context.Context, arg InsertAutoCategoryLinkBySellerInnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAutoCategoryLinkBySellerInn, arg.CategoryID, arg.SellerInn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertReceiptCategoryLink = `-- name: InsertReceiptCategoryLink :exec
INSERT IGNORE INTO
  receipt_categories (receipt_id, category_id)
VALUES
  (?, ?)
`

type InsertReceiptCategoryLinkParams struct {
	ReceiptID  string `json:"receiptId"`
	CategoryID int32  `json:"categoryId"`
}

func (q *Queries) InsertReceiptCategoryLink(ctx context.Context, arg InsertReceiptCategoryLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertReceiptCategoryLink, arg.ReceiptID, arg.CategoryID)
	return err
}

const listAllReceiptCategoryLinks = `-- name: ListAllReceiptCategoryLinks :many
SELECT
  receipt_id,
  category_id
FROM
  receipt_categories
ORDER BY
  category_id
`

func (q *Queries) ListAllReceiptCategoryLinks(ctx context.Context) ([]ReceiptCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAllReceiptCategoryLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptCategory
	for rows.Next() {
		var i ReceiptCategory
		if err := rows.Scan(&i.ReceiptID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many

SELECT
  id, name, is_system
FROM
  categories
ORDER BY
  name
`

// ============================================
// categories / merchant_category / keyword_category
// (авто-категоризация чеков, см. internal/receipt_category)
// ============================================
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.IsSystem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeywordCategories = `-- name: ListKeywordCategories :many
SELECT
  keyword, category_id, is_system
FROM
  keyword_category
`

func (q *Queries) ListKeywordCategories(ctx context.Context) ([]KeywordCategory, error) {
	rows, err := q.db.QueryContext(ctx, listKeywordCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeywordCategory
	for rows.Next() {
		var i KeywordCategory
		if err := rows.Scan(&i.Keyword, &i.CategoryID, &i.IsSystem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantCategories = `-- name: ListMerchantCategories :many
SELECT
  mc.inn,
  mc.category_id,
  mc.source,
  (
    SELECT
      r.seller_name
    FROM
      receipts r
    WHERE
      r.seller_inn = mc.inn
    ORDER BY
      (r.seller_name IS NULL) ASC,
      r.ticket_date DESC
    LIMIT
      1
  ) AS seller_name
FROM
  merchant_category mc
ORDER BY
  mc.inn
`

type ListMerchantCategoriesRow struct {
	Inn        string         `json:"inn"`
	CategoryID int32          `json:"categoryId"`
	Source     string         `json:"source"`
	SellerName sql.NullString `json:"sellerName"`
}

// seller_name — не своя колонка (merchant_category знает только ИНН), берём
// с чека этого продавца, просто для отображения в UI (см. экран настроек
// "Категории и слова" -> "Продавцы"). Сортируем по ticket_date (дата самой
// покупки), а не updated_at — тот меняется у всех чеков разом при массовой
// перекатегоризации (BackfillCategories/UpdateMerchant), из-за чего "самый
// свежий" чек и его seller_name раньше менялись от одного этого, а не от
// новых покупок. seller_name IS NULL — в конец, чтобы не показывать пусто,
// когда есть чек с реальным именем продавца.
func (q *Queries) ListMerchantCategories(ctx context.Context) ([]ListMerchantCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMerchantCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMerchantCategoriesRow
	for rows.Next() {
		var i ListMerchantCategoriesRow
		if err := rows.Scan(
			&i.Inn,
			&i.CategoryID,
			&i.Source,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptCategoryIDs = `-- name: ListReceiptCategoryIDs :many
SELECT
  category_id
FROM
  receipt_categories
WHERE
  receipt_id = ?
ORDER BY
  category_id
`

func (q *Queries) ListReceiptCategoryIDs(ctx context.Context, receiptID string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptCategoryIDs, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var category_id int32
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptCategoryLinksByUser = `-- name: ListReceiptCategoryLinksByUser :many
SELECT
  rc.receipt_id,
  rc.category_id
FROM
  receipt_categories rc
  JOIN receipts r ON r.id = rc.receipt_id
WHERE
  r.user_id = ?
ORDER BY
  rc.category_id
`

func (q *Queries) ListReceiptCategoryLinksByUser(ctx context.Context, userID string) ([]ReceiptCategory, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptCategoryLinksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptCategory
	for rows.Next() {
		var i ReceiptCategory
		if err := rows.Scan(&i.ReceiptID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCategory = `-- name: RenameCategory :exec
UPDATE categories
SET
  name = ?
WHERE
  id = ?
`

type RenameCategoryParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) error {
	_, err := q.db.ExecContext(ctx, renameCategory, arg.Name, arg.ID)
	return err
}

const setReceiptCategoriesManual = `-- name: SetReceiptCategoriesManual :exec
UPDATE receipts
SET
  categories_manual = ?,
  updated_at = ?
WHERE
  id = ?
`

type SetReceiptCategoriesManualParams struct {
	CategoriesManual bool      `json:"categoriesManual"`
	UpdatedAt        time.Time `json:"updatedAt"`
	ID               string    `json:"id"`
}

func (q *Queries) SetReceiptCategoriesManual(ctx context.Context, arg SetReceiptCategoriesManualParams) error {
	_, err := q.db.ExecContext(ctx, setReceiptCategoriesManual, arg.CategoriesManual, arg.UpdatedAt, arg.ID)
	return err
}

const upsertMerchantCategory = `-- name: UpsertMerchantCategory :exec
INSERT INTO
  merchant_category (inn, category_id, source)
VALUES
  (?, ?, ?) ON DUPLICATE KEY
UPDATE category_id =
VALUES
  (category_id),
  source =
VALUES
  (source)
`

type UpsertMerchantCategoryParams struct {
	Inn        string `json:"inn"`
	CategoryID int32  `json:"categoryId"`
	Source     string `json:"source"`
}

func (q *Queries) UpsertMerchantCategory(ctx context.Context, arg UpsertMerchantCategoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMerchantCategory, arg.Inn, arg.CategoryID, arg.Source)
	return err
}
