// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sick_leave.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createSickLeave = `-- name: CreateSickLeave :exec
INSERT INTO sick_leaves (user_id, start_date, end_date, total_days, description, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSickLeaveParams struct {
	UserID      string           `json:"userId"`
	StartDate   time.Time        `json:"startDate"`
	EndDate     time.Time        `json:"endDate"`
	TotalDays   int32            `json:"totalDays"`
	Description sql.NullString   `json:"description"`
	Status      SickLeavesStatus `json:"status"`
}

func (q *Queries) CreateSickLeave(ctx context.Context, arg CreateSickLeaveParams) error {
	_, err := q.db.ExecContext(ctx, createSickLeave,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.TotalDays,
		arg.Description,
		arg.Status,
	)
	return err
}

const getSickLeaveByID = `-- name: GetSickLeaveByID :one
SELECT
    id,
    user_id,
    start_date,
    end_date,
    total_days,
    COALESCE(description, '') as description,
    status,
    created_at,
    updated_at
FROM sick_leaves
WHERE id = ?
`

type GetSickLeaveByIDRow struct {
	ID          string           `json:"id"`
	UserID      string           `json:"userId"`
	StartDate   time.Time        `json:"startDate"`
	EndDate     time.Time        `json:"endDate"`
	TotalDays   int32            `json:"totalDays"`
	Description string           `json:"description"`
	Status      SickLeavesStatus `json:"status"`
	CreatedAt   sql.NullTime     `json:"createdAt"`
	UpdatedAt   sql.NullTime     `json:"updatedAt"`
}

func (q *Queries) GetSickLeaveByID(ctx context.Context, id string) (GetSickLeaveByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSickLeaveByID, id)
	var i GetSickLeaveByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalDays,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSickLeavesByYear = `-- name: GetSickLeavesByYear :many
SELECT
    id,
    user_id,
    start_date,
    end_date,
    total_days,
    COALESCE(description, '') as description,
    status,
    created_at,
    updated_at
FROM sick_leaves
WHERE user_id = ?
    AND YEAR(start_date) = YEAR(?)
    AND YEAR(end_date) = YEAR(?)
ORDER BY created_at DESC
`

type GetSickLeavesByYearParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
}

type GetSickLeavesByYearRow struct {
	ID          string           `json:"id"`
	UserID      string           `json:"userId"`
	StartDate   time.Time        `json:"startDate"`
	EndDate     time.Time        `json:"endDate"`
	TotalDays   int32            `json:"totalDays"`
	Description string           `json:"description"`
	Status      SickLeavesStatus `json:"status"`
	CreatedAt   sql.NullTime     `json:"createdAt"`
	UpdatedAt   sql.NullTime     `json:"updatedAt"`
}

func (q *Queries) GetSickLeavesByYear(ctx context.Context, arg GetSickLeavesByYearParams) ([]GetSickLeavesByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getSickLeavesByYear, arg.UserID, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSickLeavesByYearRow
	for rows.Next() {
		var i GetSickLeavesByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const getAllUsersSickLeavesByYear = `-- name: GetAllUsersSickLeavesByYear :many
SELECT
    id,
    user_id,
    start_date,
    end_date,
    total_days,
    COALESCE(description, '') as description,
    status,
    created_at,
    updated_at
FROM sick_leaves
WHERE YEAR(start_date) = YEAR(?)
    AND YEAR(end_date) = YEAR(?)
ORDER BY created_at DESC
`

type GetAllUsersSickLeavesByYearParams struct {
	Year time.Time `json:"year"`
}

type GetAllUsersSickLeavesByYearRow struct {
	ID          string           `json:"id"`
	UserID      string           `json:"userId"`
	StartDate   time.Time        `json:"startDate"`
	EndDate     time.Time        `json:"endDate"`
	TotalDays   int32            `json:"totalDays"`
	Description string           `json:"description"`
	Status      SickLeavesStatus `json:"status"`
	CreatedAt   sql.NullTime     `json:"createdAt"`
	UpdatedAt   sql.NullTime     `json:"updatedAt"`
}

func (q *Queries) GetAllUsersSickLeavesByYear(ctx context.Context, arg GetAllUsersSickLeavesByYearParams) ([]GetAllUsersSickLeavesByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersSickLeavesByYear, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersSickLeavesByYearRow
	for rows.Next() {
		var i GetAllUsersSickLeavesByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	return items, rows.Err()
}

const getCountSickLeavesByStatus = `-- name: GetCountSickLeavesByStatus :one
SELECT COALESCE(SUM(total_days), 0) as total_days
FROM sick_leaves
WHERE user_id = ?
  AND status = ?
  AND YEAR(start_date) = YEAR(?)
`

type GetCountSickLeavesByStatusParams struct {
	UserID string           `json:"userId"`
	Status SickLeavesStatus `json:"status"`
	Year   time.Time        `json:"year"`
}

func (q *Queries) GetCountSickLeavesByStatus(ctx context.Context, arg GetCountSickLeavesByStatusParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCountSickLeavesByStatus, arg.UserID, arg.Status, arg.Year)
	var totalDays interface{}
	err := row.Scan(&totalDays)
	return totalDays, err
}

const updateSickLeaveStatus = `-- name: UpdateSickLeaveStatus :exec
UPDATE sick_leaves
SET status = ?
WHERE id = ?
`

type UpdateSickLeaveStatusParams struct {
	Status SickLeavesStatus `json:"status"`
	ID     string           `json:"id"`
}

func (q *Queries) UpdateSickLeaveStatus(ctx context.Context, arg UpdateSickLeaveStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSickLeaveStatus, arg.Status, arg.ID)
	return err
}

const deleteSickLeave = `-- name: DeleteSickLeave :exec
DELETE FROM sick_leaves WHERE id = ?
`

func (q *Queries) DeleteSickLeave(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSickLeave, id)
	return err
}
