// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package repo

import (
	"context"
	"database/sql"
)

const createSystemSetting = `-- name: CreateSystemSetting :exec
INSERT INTO system_settings (setting_key, setting_value, setting_type, category, description, is_public)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSystemSettingParams struct {
	SettingKey   string                        `json:"settingKey"`
	SettingValue sql.NullString                `json:"settingValue"`
	SettingType  NullSystemSettingsSettingType `json:"settingType"`
	Category     sql.NullString                `json:"category"`
	Description  sql.NullString                `json:"description"`
	IsPublic     sql.NullBool                  `json:"isPublic"`
}

func (q *Queries) CreateSystemSetting(ctx context.Context, arg CreateSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, createSystemSetting,
		arg.SettingKey,
		arg.SettingValue,
		arg.SettingType,
		arg.Category,
		arg.Description,
		arg.IsPublic,
	)
	return err
}

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings WHERE setting_key = ?
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, settingKey string) error {
	_, err := q.db.ExecContext(ctx, deleteSystemSetting, settingKey)
	return err
}

const getPublicSystemSettings = `-- name: GetPublicSystemSettings :many
SELECT id, setting_key, setting_value, setting_type, category, description, is_public, created_at, updated_at FROM system_settings WHERE is_public = 1
`

func (q *Queries) GetPublicSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, getPublicSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.SettingKey,
			&i.SettingValue,
			&i.SettingType,
			&i.Category,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemSettingByKey = `-- name: GetSystemSettingByKey :one
SELECT id, setting_key, setting_value, setting_type, category, description, is_public, created_at, updated_at FROM system_settings WHERE setting_key = ?
`

func (q *Queries) GetSystemSettingByKey(ctx context.Context, settingKey string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSettingByKey, settingKey)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.SettingKey,
		&i.SettingValue,
		&i.SettingType,
		&i.Category,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSettingByKeyAndCategory = `-- name: GetSystemSettingByKeyAndCategory :one
SELECT id, setting_key, setting_value, setting_type, category, description, is_public, created_at, updated_at FROM system_settings WHERE setting_key = ? AND category = ?
`

type GetSystemSettingByKeyAndCategoryParams struct {
	SettingKey string         `json:"settingKey"`
	Category   sql.NullString `json:"category"`
}

func (q *Queries) GetSystemSettingByKeyAndCategory(ctx context.Context, arg GetSystemSettingByKeyAndCategoryParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSettingByKeyAndCategory, arg.SettingKey, arg.Category)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.SettingKey,
		&i.SettingValue,
		&i.SettingType,
		&i.Category,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSettings = `-- name: GetSystemSettings :many

SELECT id, setting_key, setting_value, setting_type, category, description, is_public, created_at, updated_at FROM system_settings
`

// ============================================
// system_settings queries
// ============================================
func (q *Queries) GetSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, getSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.SettingKey,
			&i.SettingValue,
			&i.SettingType,
			&i.Category,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemSettingsByCategory = `-- name: GetSystemSettingsByCategory :many
SELECT id, setting_key, setting_value, setting_type, category, description, is_public, created_at, updated_at FROM system_settings WHERE category = ?
`

func (q *Queries) GetSystemSettingsByCategory(ctx context.Context, category sql.NullString) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, getSystemSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.SettingKey,
			&i.SettingValue,
			&i.SettingType,
			&i.Category,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemSetting = `-- name: UpdateSystemSetting :exec
UPDATE system_settings
SET setting_value = ?, setting_type = ?, category = ?, description = ?, is_public = ?, updated_at = CURRENT_TIMESTAMP
WHERE setting_key = ?
`

type UpdateSystemSettingParams struct {
	SettingValue sql.NullString                `json:"settingValue"`
	SettingType  NullSystemSettingsSettingType `json:"settingType"`
	Category     sql.NullString                `json:"category"`
	Description  sql.NullString                `json:"description"`
	IsPublic     sql.NullBool                  `json:"isPublic"`
	SettingKey   string                        `json:"settingKey"`
}

func (q *Queries) UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemSetting,
		arg.SettingValue,
		arg.SettingType,
		arg.Category,
		arg.Description,
		arg.IsPublic,
		arg.SettingKey,
	)
	return err
}

const updateValueSystemSetting = `-- name: UpdateValueSystemSetting :exec
UPDATE system_settings
SET setting_value = ?
WHERE setting_key = ?
`

type UpdateValueSystemSettingParams struct {
	SettingValue sql.NullString `json:"settingValue"`
	SettingKey   string         `json:"settingKey"`
}

func (q *Queries) UpdateValueSystemSetting(ctx context.Context, arg UpdateValueSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateValueSystemSetting, arg.SettingValue, arg.SettingKey)
	return err
}
