// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheet_reminder.sql

package repo

import (
	"context"
	"database/sql"
)

const countNotificationsSentToday = `-- name: CountNotificationsSentToday :one
SELECT
  COUNT(*)
FROM
  notifications
WHERE
  user_id = ?
  AND entity_type = ?
  AND entity_id = ?
  AND DATE(created_at) = DATE(UTC_TIMESTAMP())
`

type CountNotificationsSentTodayParams struct {
	UserID     string         `json:"userId"`
	EntityType sql.NullString `json:"entityType"`
	EntityID   sql.NullString `json:"entityId"`
}

// Дедуп: не слать напоминание повторно в тот же день (DATE() по UTC —
// created_at теперь буквальный UTC, см. 018_notification_timestamp_utc.sql).
func (q *Queries) CountNotificationsSentToday(ctx context.Context, arg CountNotificationsSentTodayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsSentToday, arg.UserID, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listKnownUserIDs = `-- name: ListKnownUserIDs :many
SELECT
  user_id
FROM
  user_time_entries
GROUP BY
  user_id
UNION
SELECT
  user_id
FROM
  work_standards
WHERE
  user_id IS NOT NULL
GROUP BY
  user_id
`

// Сотрудники, о которых бэк вообще что-то знает локально (без похода в
// auth-сервис за полным списком — см. internal/timesheetreminder) — кто
// хоть раз вносил запись в табель, либо кому задан индивидуальный график.
// Ограничение: сотрудник, который вообще ничего ни разу не вносил, сюда не
// попадёт — и не получит напоминание, хотя ему оно нужнее всего.
func (q *Queries) ListKnownUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnownUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
