// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_vk_links.sql

package repo

import (
	"context"
	"strings"
)

const getUserByVKID = `-- name: GetUserByVKID :one
SELECT
  user_id
FROM
  user_vk_links
WHERE
  vk_user_id = ?
`

func (q *Queries) GetUserByVKID(ctx context.Context, vkUserID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserByVKID, vkUserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getVKIDByUser = `-- name: GetVKIDByUser :one
SELECT
  vk_user_id
FROM
  user_vk_links
WHERE
  user_id = ?
`

func (q *Queries) GetVKIDByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVKIDByUser, userID)
	var vk_user_id int64
	err := row.Scan(&vk_user_id)
	return vk_user_id, err
}

const linkUserVK = `-- name: LinkUserVK :exec
INSERT INTO
  user_vk_links (user_id, vk_user_id, created_at)
VALUES
  (?, ?, UTC_TIMESTAMP()) ON DUPLICATE KEY
UPDATE vk_user_id =
VALUES
  (vk_user_id)
`

type LinkUserVKParams struct {
	UserID   string `json:"userId"`
	VkUserID int64  `json:"vkUserId"`
}

func (q *Queries) LinkUserVK(ctx context.Context, arg LinkUserVKParams) error {
	_, err := q.db.ExecContext(ctx, linkUserVK, arg.UserID, arg.VkUserID)
	return err
}

const listVKIDsByUsers = `-- name: ListVKIDsByUsers :many
SELECT
  user_id,
  vk_user_id
FROM
  user_vk_links
WHERE
  user_id IN (/*SLICE:user_ids*/?)
`

type ListVKIDsByUsersRow struct {
	UserID   string `json:"userId"`
	VkUserID int64  `json:"vkUserId"`
}

// Пакетно для рассылки уведомлений участникам чата одним запросом вместо
// N+1 (по аналогии с ListFilesByEntityIDs в file_entity_refs.sql).
func (q *Queries) ListVKIDsByUsers(ctx context.Context, userIds []string) ([]ListVKIDsByUsersRow, error) {
	query := listVKIDsByUsers
	var queryParams []interface{}
	if len(userIds) > 0 {
		for _, v := range userIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(userIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVKIDsByUsersRow
	for rows.Next() {
		var i ListVKIDsByUsersRow
		if err := rows.Scan(&i.UserID, &i.VkUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkUserVK = `-- name: UnlinkUserVK :exec
DELETE FROM user_vk_links
WHERE
  user_id = ?
`

func (q *Queries) UnlinkUserVK(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, unlinkUserVK, userID)
	return err
}
