// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_time_entries.sql

package repo

import (
	"context"
	"strings"
	"time"
)

const createUserTimeEntry = `-- name: CreateUserTimeEntry :exec
INSERT INTO user_time_entries (user_id, entry_date, day_type_id, hours_worked)
VALUES (?, ?, ?, ?)
`

type CreateUserTimeEntryParams struct {
	UserID      string    `json:"userId"`
	EntryDate   time.Time `json:"entryDate"`
	DayTypeID   string    `json:"dayTypeId"`
	HoursWorked string    `json:"hoursWorked"`
}

func (q *Queries) CreateUserTimeEntry(ctx context.Context, arg CreateUserTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, createUserTimeEntry,
		arg.UserID,
		arg.EntryDate,
		arg.DayTypeID,
		arg.HoursWorked,
	)
	return err
}

const deleteUserTimeEntries = `-- name: DeleteUserTimeEntries :exec
DELETE FROM user_time_entries WHERE entry_date IN (/*SLICE:entry_date*/?) AND user_id = ?
`

type DeleteUserTimeEntriesParams struct {
	EntryDate []time.Time `json:"entryDate"`
	UserID    string      `json:"userId"`
}

func (q *Queries) DeleteUserTimeEntries(ctx context.Context, arg DeleteUserTimeEntriesParams) error {
	query := deleteUserTimeEntries
	var queryParams []interface{}
	if len(arg.EntryDate) > 0 {
		for _, v := range arg.EntryDate {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:entry_date*/?", strings.Repeat(",?", len(arg.EntryDate))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:entry_date*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteUserTimeEntry = `-- name: DeleteUserTimeEntry :exec
DELETE FROM user_time_entries WHERE entry_date = ? AND user_id = ?
`

type DeleteUserTimeEntryParams struct {
	EntryDate time.Time `json:"entryDate"`
	UserID    string    `json:"userId"`
}

func (q *Queries) DeleteUserTimeEntry(ctx context.Context, arg DeleteUserTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserTimeEntry, arg.EntryDate, arg.UserID)
	return err
}

const getTotalDaysByMonthWithSystemName = `-- name: GetTotalDaysByMonthWithSystemName :one
SELECT
    COUNT(ute.entry_date) as total_days
FROM user_time_entries ute
JOIN day_types dt ON ute.day_type_id = dt.id
WHERE ute.user_id = ?
    AND YEAR(ute.entry_date) = YEAR(?)
    AND MONTH(ute.entry_date) = MONTH(?)
    AND dt.system_name = ?
GROUP BY ute.user_id, YEAR(ute.entry_date), MONTH(ute.entry_date)
`

type GetTotalDaysByMonthWithSystemNameParams struct {
	UserID     string    `json:"userId"`
	Year       time.Time `json:"year"`
	Month      time.Time `json:"month"`
	SystemName string    `json:"systemName"`
}

func (q *Queries) GetTotalDaysByMonthWithSystemName(ctx context.Context, arg GetTotalDaysByMonthWithSystemNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalDaysByMonthWithSystemName,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.SystemName,
	)
	var total_days int64
	err := row.Scan(&total_days)
	return total_days, err
}

const getTotalDaysByYearWithSystemName = `-- name: GetTotalDaysByYearWithSystemName :one
SELECT
    COUNT(ute.entry_date) as total_days
FROM user_time_entries ute
JOIN day_types dt ON ute.day_type_id = dt.id
WHERE ute.user_id = ?
    AND YEAR(ute.entry_date) = YEAR(?)
    AND dt.system_name = ?
GROUP BY ute.user_id, YEAR(ute.entry_date)
`

type GetTotalDaysByYearWithSystemNameParams struct {
	UserID     string    `json:"userId"`
	Year       time.Time `json:"year"`
	SystemName string    `json:"systemName"`
}

func (q *Queries) GetTotalDaysByYearWithSystemName(ctx context.Context, arg GetTotalDaysByYearWithSystemNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalDaysByYearWithSystemName, arg.UserID, arg.Year, arg.SystemName)
	var total_days int64
	err := row.Scan(&total_days)
	return total_days, err
}

const getTotalHoursByMonth = `-- name: GetTotalHoursByMonth :one
SELECT
    SUM(hours_worked) as total_hours
FROM user_time_entries
WHERE user_id = ? AND YEAR(entry_date) = YEAR(?) AND MONTH(entry_date) = MONTH(?)
GROUP BY user_id, YEAR(entry_date), MONTH(entry_date)
`

type GetTotalHoursByMonthParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
	Month  time.Time `json:"month"`
}

func (q *Queries) GetTotalHoursByMonth(ctx context.Context, arg GetTotalHoursByMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalHoursByMonth, arg.UserID, arg.Year, arg.Month)
	var total_hours interface{}
	err := row.Scan(&total_hours)
	return total_hours, err
}

const getTotalHoursByYear = `-- name: GetTotalHoursByYear :one
SELECT
    SUM(hours_worked) as total_hours
FROM user_time_entries
WHERE user_id = ? AND YEAR(entry_date) = YEAR(?)
GROUP BY user_id, YEAR(entry_date)
`

type GetTotalHoursByYearParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
}

func (q *Queries) GetTotalHoursByYear(ctx context.Context, arg GetTotalHoursByYearParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalHoursByYear, arg.UserID, arg.Year)
	var total_hours interface{}
	err := row.Scan(&total_hours)
	return total_hours, err
}

const getUserTimeEntriesForMonth = `-- name: GetUserTimeEntriesForMonth :many

SELECT id, user_id, entry_date, day_type_id, hours_worked, created_at, updated_at
FROM user_time_entries
WHERE user_id = ? AND YEAR(entry_date) = YEAR(?) AND MONTH(entry_date) = MONTH(?)
ORDER BY entry_date
`

type GetUserTimeEntriesForMonthParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
	Month  time.Time `json:"month"`
}

// ============================================
// user_time_entries queries
// ============================================
func (q *Queries) GetUserTimeEntriesForMonth(ctx context.Context, arg GetUserTimeEntriesForMonthParams) ([]UserTimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, getUserTimeEntriesForMonth, arg.UserID, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTimeEntry
	for rows.Next() {
		var i UserTimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.DayTypeID,
			&i.HoursWorked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTimeEntryById = `-- name: GetUserTimeEntryById :one
SELECT id, user_id, entry_date, day_type_id, hours_worked, created_at, updated_at
FROM user_time_entries
WHERE id = ?
`

func (q *Queries) GetUserTimeEntryById(ctx context.Context, id string) (UserTimeEntry, error) {
	row := q.db.QueryRowContext(ctx, getUserTimeEntryById, id)
	var i UserTimeEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryDate,
		&i.DayTypeID,
		&i.HoursWorked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTimeEntryByIds = `-- name: GetUserTimeEntryByIds :many
SELECT id, user_id, entry_date, day_type_id, hours_worked, created_at, updated_at
FROM user_time_entries
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetUserTimeEntryByIds(ctx context.Context, ids []string) ([]UserTimeEntry, error) {
	query := getUserTimeEntryByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTimeEntry
	for rows.Next() {
		var i UserTimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryDate,
			&i.DayTypeID,
			&i.HoursWorked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkDaysByMonth = `-- name: GetWorkDaysByMonth :one
SELECT
    COUNT(DISTINCT entry_date) as total_days
FROM user_time_entries
WHERE user_id = ?
    AND YEAR(entry_date) = YEAR(?)
    AND MONTH(entry_date) = MONTH(?)
    AND hours_worked > 0
`

type GetWorkDaysByMonthParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
	Month  time.Time `json:"month"`
}

func (q *Queries) GetWorkDaysByMonth(ctx context.Context, arg GetWorkDaysByMonthParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWorkDaysByMonth, arg.UserID, arg.Year, arg.Month)
	var total_days int64
	err := row.Scan(&total_days)
	return total_days, err
}

const updateUserTimeEntries = `-- name: UpdateUserTimeEntries :exec
UPDATE user_time_entries
SET
    day_type_id = ?,
    hours_worked = ?
WHERE entry_date IN (/*SLICE:entry_date*/?) AND user_id = ?
`

type UpdateUserTimeEntriesParams struct {
	DayTypeID   string      `json:"dayTypeId"`
	HoursWorked string      `json:"hoursWorked"`
	EntryDate   []time.Time `json:"entryDate"`
	UserID      string      `json:"userId"`
}

func (q *Queries) UpdateUserTimeEntries(ctx context.Context, arg UpdateUserTimeEntriesParams) error {
	query := updateUserTimeEntries
	var queryParams []interface{}
	queryParams = append(queryParams, arg.DayTypeID)
	queryParams = append(queryParams, arg.HoursWorked)
	if len(arg.EntryDate) > 0 {
		for _, v := range arg.EntryDate {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:entry_date*/?", strings.Repeat(",?", len(arg.EntryDate))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:entry_date*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateUserTimeEntry = `-- name: UpdateUserTimeEntry :exec
UPDATE user_time_entries
SET
    day_type_id = ?,
    hours_worked = ?
WHERE entry_date = ? AND user_id = ?
`

type UpdateUserTimeEntryParams struct {
	DayTypeID   string    `json:"dayTypeId"`
	HoursWorked string    `json:"hoursWorked"`
	EntryDate   time.Time `json:"entryDate"`
	UserID      string    `json:"userId"`
}

func (q *Queries) UpdateUserTimeEntry(ctx context.Context, arg UpdateUserTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTimeEntry,
		arg.DayTypeID,
		arg.HoursWorked,
		arg.EntryDate,
		arg.UserID,
	)
	return err
}
