// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vacation.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const assignVacationType = `-- name: AssignVacationType :exec
UPDATE vacations
SET
  vacation_type_id = ?
WHERE
  id = ?
`

type AssignVacationTypeParams struct {
	VacationTypeID sql.NullString `json:"vacationTypeId"`
	ID             string         `json:"id"`
}

func (q *Queries) AssignVacationType(ctx context.Context, arg AssignVacationTypeParams) error {
	_, err := q.db.ExecContext(ctx, assignVacationType, arg.VacationTypeID, arg.ID)
	return err
}

const createVacation = `-- name: CreateVacation :exec
INSERT INTO
  vacations (
    user_id,
    start_date,
    end_date,
    total_days,
    description,
    status,
    vacation_type_id
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?)
`

type CreateVacationParams struct {
	UserID         string          `json:"userId"`
	StartDate      time.Time       `json:"startDate"`
	EndDate        time.Time       `json:"endDate"`
	TotalDays      int32           `json:"totalDays"`
	Description    sql.NullString  `json:"description"`
	Status         VacationsStatus `json:"status"`
	VacationTypeID sql.NullString  `json:"vacationTypeId"`
}

func (q *Queries) CreateVacation(ctx context.Context, arg CreateVacationParams) error {
	_, err := q.db.ExecContext(ctx, createVacation,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.TotalDays,
		arg.Description,
		arg.Status,
		arg.VacationTypeID,
	)
	return err
}

const deleteVacation = `-- name: DeleteVacation :exec
DELETE FROM vacations
WHERE
  id = ?
`

func (q *Queries) DeleteVacation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVacation, id)
	return err
}

const getAllUsersVacationsByYear = `-- name: GetAllUsersVacationsByYear :many
SELECT
  v.id,
  v.user_id,
  v.start_date,
  v.end_date,
  v.total_days,
  COALESCE(v.description, '') as description,
  v.status,
  v.vacation_type_id,
  COALESCE(t.name, '') as vacation_type_name,
  COALESCE(t.color_code, '') as vacation_type_color,
  COALESCE(t.affects_balance, TRUE) as vacation_type_affects_balance,
  v.created_at,
  v.updated_at
FROM
  vacations v
  LEFT JOIN vacation_types t ON t.id = v.vacation_type_id
WHERE
  YEAR(v.start_date) = YEAR(?)
  AND YEAR(v.end_date) = YEAR(?)
ORDER BY
  v.created_at DESC
`

type GetAllUsersVacationsByYearParams struct {
	Year time.Time `json:"year"`
}

type GetAllUsersVacationsByYearRow struct {
	ID                         string          `json:"id"`
	UserID                     string          `json:"userId"`
	StartDate                  time.Time       `json:"startDate"`
	EndDate                    time.Time       `json:"endDate"`
	TotalDays                  int32           `json:"totalDays"`
	Description                string          `json:"description"`
	Status                     VacationsStatus `json:"status"`
	VacationTypeID             sql.NullString  `json:"vacationTypeId"`
	VacationTypeName           string          `json:"vacationTypeName"`
	VacationTypeColor          string          `json:"vacationTypeColor"`
	VacationTypeAffectsBalance bool            `json:"vacationTypeAffectsBalance"`
	CreatedAt                  sql.NullTime    `json:"createdAt"`
	UpdatedAt                  sql.NullTime    `json:"updatedAt"`
}

func (q *Queries) GetAllUsersVacationsByYear(ctx context.Context, arg GetAllUsersVacationsByYearParams) ([]GetAllUsersVacationsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersVacationsByYear, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersVacationsByYearRow
	for rows.Next() {
		var i GetAllUsersVacationsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Description,
			&i.Status,
			&i.VacationTypeID,
			&i.VacationTypeName,
			&i.VacationTypeColor,
			&i.VacationTypeAffectsBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountVacationsByStatus = `-- name: GetCountVacationsByStatus :one
SELECT
  COALESCE(SUM(v.total_days), 0) as total_days
FROM
  vacations v
  LEFT JOIN vacation_types t ON t.id = v.vacation_type_id
WHERE
  v.user_id = ?
  AND v.status = ?
  AND YEAR(v.start_date) = YEAR(?)
  AND COALESCE(t.affects_balance, TRUE) = TRUE
`

type GetCountVacationsByStatusParams struct {
	UserID string          `json:"userId"`
	Status VacationsStatus `json:"status"`
	Year   time.Time       `json:"year"`
}

func (q *Queries) GetCountVacationsByStatus(ctx context.Context, arg GetCountVacationsByStatusParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCountVacationsByStatus, arg.UserID, arg.Status, arg.Year)
	var total_days interface{}
	err := row.Scan(&total_days)
	return total_days, err
}

const getVacationByID = `-- name: GetVacationByID :one
SELECT
  v.id,
  v.user_id,
  v.start_date,
  v.end_date,
  v.total_days,
  COALESCE(v.description, '') as description,
  v.status,
  v.vacation_type_id,
  COALESCE(t.name, '') as vacation_type_name,
  COALESCE(t.color_code, '') as vacation_type_color,
  COALESCE(t.affects_balance, TRUE) as vacation_type_affects_balance,
  v.created_at,
  v.updated_at
FROM
  vacations v
  LEFT JOIN vacation_types t ON t.id = v.vacation_type_id
WHERE
  v.id = ?
`

type GetVacationByIDRow struct {
	ID                         string          `json:"id"`
	UserID                     string          `json:"userId"`
	StartDate                  time.Time       `json:"startDate"`
	EndDate                    time.Time       `json:"endDate"`
	TotalDays                  int32           `json:"totalDays"`
	Description                string          `json:"description"`
	Status                     VacationsStatus `json:"status"`
	VacationTypeID             sql.NullString  `json:"vacationTypeId"`
	VacationTypeName           string          `json:"vacationTypeName"`
	VacationTypeColor          string          `json:"vacationTypeColor"`
	VacationTypeAffectsBalance bool            `json:"vacationTypeAffectsBalance"`
	CreatedAt                  sql.NullTime    `json:"createdAt"`
	UpdatedAt                  sql.NullTime    `json:"updatedAt"`
}

func (q *Queries) GetVacationByID(ctx context.Context, id string) (GetVacationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVacationByID, id)
	var i GetVacationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalDays,
		&i.Description,
		&i.Status,
		&i.VacationTypeID,
		&i.VacationTypeName,
		&i.VacationTypeColor,
		&i.VacationTypeAffectsBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVacationsByYear = `-- name: GetVacationsByYear :many
SELECT
  v.id,
  v.user_id,
  v.start_date,
  v.end_date,
  v.total_days,
  COALESCE(v.description, '') as description,
  v.status,
  v.vacation_type_id,
  COALESCE(t.name, '') as vacation_type_name,
  COALESCE(t.color_code, '') as vacation_type_color,
  COALESCE(t.affects_balance, TRUE) as vacation_type_affects_balance,
  v.created_at,
  v.updated_at
FROM
  vacations v
  LEFT JOIN vacation_types t ON t.id = v.vacation_type_id
WHERE
  v.user_id = ?
  AND YEAR(v.start_date) = YEAR(?)
  AND YEAR(v.end_date) = YEAR(?)
ORDER BY
  v.created_at DESC
`

type GetVacationsByYearParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
}

type GetVacationsByYearRow struct {
	ID                         string          `json:"id"`
	UserID                     string          `json:"userId"`
	StartDate                  time.Time       `json:"startDate"`
	EndDate                    time.Time       `json:"endDate"`
	TotalDays                  int32           `json:"totalDays"`
	Description                string          `json:"description"`
	Status                     VacationsStatus `json:"status"`
	VacationTypeID             sql.NullString  `json:"vacationTypeId"`
	VacationTypeName           string          `json:"vacationTypeName"`
	VacationTypeColor          string          `json:"vacationTypeColor"`
	VacationTypeAffectsBalance bool            `json:"vacationTypeAffectsBalance"`
	CreatedAt                  sql.NullTime    `json:"createdAt"`
	UpdatedAt                  sql.NullTime    `json:"updatedAt"`
}

func (q *Queries) GetVacationsByYear(ctx context.Context, arg GetVacationsByYearParams) ([]GetVacationsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getVacationsByYear, arg.UserID, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVacationsByYearRow
	for rows.Next() {
		var i GetVacationsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Description,
			&i.Status,
			&i.VacationTypeID,
			&i.VacationTypeName,
			&i.VacationTypeColor,
			&i.VacationTypeAffectsBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacationStatus = `-- name: UpdateVacationStatus :exec
UPDATE vacations
SET
  status = ?
WHERE
  id = ?
`

type UpdateVacationStatusParams struct {
	Status VacationsStatus `json:"status"`
	ID     string          `json:"id"`
}

func (q *Queries) UpdateVacationStatus(ctx context.Context, arg UpdateVacationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVacationStatus, arg.Status, arg.ID)
	return err
}
