// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vacation.sql

package repo

import (
	"context"
	"database/sql"
	"time"
)

const createVacation = `-- name: CreateVacation :exec
INSERT INTO vacations (user_id, start_date, end_date, total_days, description, doc_file_name, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVacationParams struct {
	UserID      string          `json:"userId"`
	StartDate   time.Time       `json:"startDate"`
	EndDate     time.Time       `json:"endDate"`
	TotalDays   int32           `json:"totalDays"`
	Description sql.NullString  `json:"description"`
	DocFileName sql.NullString  `json:"docFileName"`
	Status      VacationsStatus `json:"status"`
}

func (q *Queries) CreateVacation(ctx context.Context, arg CreateVacationParams) error {
	_, err := q.db.ExecContext(ctx, createVacation,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.TotalDays,
		arg.Description,
		arg.DocFileName,
		arg.Status,
	)
	return err
}

const deleteVacation = `-- name: DeleteVacation :exec
DELETE FROM vacations WHERE id = ?
`

func (q *Queries) DeleteVacation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVacation, id)
	return err
}

const getAllUsersVacationsByYear = `-- name: GetAllUsersVacationsByYear :many
SELECT
    id,
    user_id,
    start_date,
    end_date,
    total_days,
    COALESCE(description, '') as description,
    COALESCE(doc_file_name, '') as doc_file_name,
    status,
    created_at,
    updated_at
FROM vacations
WHERE YEAR(start_date) = YEAR(?)
    AND YEAR(end_date) = YEAR(?)
ORDER BY created_at DESC
`

type GetAllUsersVacationsByYearParams struct {
	Year time.Time `json:"year"`
}

type GetAllUsersVacationsByYearRow struct {
	ID          string          `json:"id"`
	UserID      string          `json:"userId"`
	StartDate   time.Time       `json:"startDate"`
	EndDate     time.Time       `json:"endDate"`
	TotalDays   int32           `json:"totalDays"`
	Description string          `json:"description"`
	DocFileName string          `json:"docFileName"`
	Status      VacationsStatus `json:"status"`
	CreatedAt   sql.NullTime    `json:"createdAt"`
	UpdatedAt   sql.NullTime    `json:"updatedAt"`
}

func (q *Queries) GetAllUsersVacationsByYear(ctx context.Context, arg GetAllUsersVacationsByYearParams) ([]GetAllUsersVacationsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersVacationsByYear, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersVacationsByYearRow
	for rows.Next() {
		var i GetAllUsersVacationsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Description,
			&i.DocFileName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountVacationsByStatus = `-- name: GetCountVacationsByStatus :one
SELECT COALESCE(SUM(total_days), 0) as total_days
FROM vacations
WHERE user_id = ?
  AND status = ?
  AND YEAR(start_date) = YEAR(?)
`

type GetCountVacationsByStatusParams struct {
	UserID string          `json:"userId"`
	Status VacationsStatus `json:"status"`
	Year   time.Time       `json:"year"`
}

func (q *Queries) GetCountVacationsByStatus(ctx context.Context, arg GetCountVacationsByStatusParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCountVacationsByStatus, arg.UserID, arg.Status, arg.Year)
	var total_days interface{}
	err := row.Scan(&total_days)
	return total_days, err
}

const getVacationByID = `-- name: GetVacationByID :one
SELECT
    id,
    user_id,
    start_date,
    end_date,
    total_days,
    COALESCE(description, '') as description,
    COALESCE(doc_file_name, '') as doc_file_name,
    status,
    created_at,
    updated_at
FROM vacations
WHERE id = ?
`

type GetVacationByIDRow struct {
	ID          string          `json:"id"`
	UserID      string          `json:"userId"`
	StartDate   time.Time       `json:"startDate"`
	EndDate     time.Time       `json:"endDate"`
	TotalDays   int32           `json:"totalDays"`
	Description string          `json:"description"`
	DocFileName string          `json:"docFileName"`
	Status      VacationsStatus `json:"status"`
	CreatedAt   sql.NullTime    `json:"createdAt"`
	UpdatedAt   sql.NullTime    `json:"updatedAt"`
}

func (q *Queries) GetVacationByID(ctx context.Context, id string) (GetVacationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVacationByID, id)
	var i GetVacationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalDays,
		&i.Description,
		&i.DocFileName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVacationsByYear = `-- name: GetVacationsByYear :many
SELECT
    id,
    user_id,
    start_date,
    end_date,
    total_days,
    COALESCE(description, '') as description,
    COALESCE(doc_file_name, '') as doc_file_name,
    status,
    created_at,
    updated_at
FROM vacations
WHERE user_id = ?
    AND YEAR(start_date) = YEAR(?)
    AND YEAR(end_date) = YEAR(?)
ORDER BY created_at DESC
`

type GetVacationsByYearParams struct {
	UserID string    `json:"userId"`
	Year   time.Time `json:"year"`
}

type GetVacationsByYearRow struct {
	ID          string          `json:"id"`
	UserID      string          `json:"userId"`
	StartDate   time.Time       `json:"startDate"`
	EndDate     time.Time       `json:"endDate"`
	TotalDays   int32           `json:"totalDays"`
	Description string          `json:"description"`
	DocFileName string          `json:"docFileName"`
	Status      VacationsStatus `json:"status"`
	CreatedAt   sql.NullTime    `json:"createdAt"`
	UpdatedAt   sql.NullTime    `json:"updatedAt"`
}

func (q *Queries) GetVacationsByYear(ctx context.Context, arg GetVacationsByYearParams) ([]GetVacationsByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getVacationsByYear, arg.UserID, arg.Year, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVacationsByYearRow
	for rows.Next() {
		var i GetVacationsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Description,
			&i.DocFileName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacationFileName = `-- name: UpdateVacationFileName :exec
UPDATE vacations
SET doc_file_name = ?
WHERE id = ?
`

type UpdateVacationFileNameParams struct {
	DocFileName sql.NullString `json:"docFileName"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateVacationFileName(ctx context.Context, arg UpdateVacationFileNameParams) error {
	_, err := q.db.ExecContext(ctx, updateVacationFileName, arg.DocFileName, arg.ID)
	return err
}

const updateVacationStatus = `-- name: UpdateVacationStatus :exec
UPDATE vacations
SET status = ?
WHERE id = ?
`

type UpdateVacationStatusParams struct {
	Status VacationsStatus `json:"status"`
	ID     string          `json:"id"`
}

func (q *Queries) UpdateVacationStatus(ctx context.Context, arg UpdateVacationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVacationStatus, arg.Status, arg.ID)
	return err
}
