// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vacation_types.sql

package repo

import (
	"context"
	"database/sql"
)

const countVacationsByType = `-- name: CountVacationsByType :one
SELECT
  COUNT(*)
FROM
  vacations
WHERE
  vacation_type_id = ?
`

func (q *Queries) CountVacationsByType(ctx context.Context, vacationTypeID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVacationsByType, vacationTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVacationType = `-- name: CreateVacationType :exec
INSERT INTO
  vacation_types (
    id,
    name,
    system_name,
    color_code,
    affects_balance,
    is_active,
    sort_order
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?)
`

type CreateVacationTypeParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	SystemName     string `json:"systemName"`
	ColorCode      string `json:"colorCode"`
	AffectsBalance bool   `json:"affectsBalance"`
	IsActive       bool   `json:"isActive"`
	SortOrder      int32  `json:"sortOrder"`
}

func (q *Queries) CreateVacationType(ctx context.Context, arg CreateVacationTypeParams) error {
	_, err := q.db.ExecContext(ctx, createVacationType,
		arg.ID,
		arg.Name,
		arg.SystemName,
		arg.ColorCode,
		arg.AffectsBalance,
		arg.IsActive,
		arg.SortOrder,
	)
	return err
}

const deleteVacationType = `-- name: DeleteVacationType :exec
DELETE FROM vacation_types
WHERE
  id = ?
`

func (q *Queries) DeleteVacationType(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVacationType, id)
	return err
}

const getActiveVacationTypes = `-- name: GetActiveVacationTypes :many
SELECT
  id, name, system_name, color_code, affects_balance, is_active, sort_order, created_at, updated_at
FROM
  vacation_types
WHERE
  is_active = TRUE
ORDER BY
  sort_order,
  name
`

func (q *Queries) GetActiveVacationTypes(ctx context.Context) ([]VacationType, error) {
	rows, err := q.db.QueryContext(ctx, getActiveVacationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacationType
	for rows.Next() {
		var i VacationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemName,
			&i.ColorCode,
			&i.AffectsBalance,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVacationTypeByID = `-- name: GetVacationTypeByID :one
SELECT
  id, name, system_name, color_code, affects_balance, is_active, sort_order, created_at, updated_at
FROM
  vacation_types
WHERE
  id = ?
`

func (q *Queries) GetVacationTypeByID(ctx context.Context, id string) (VacationType, error) {
	row := q.db.QueryRowContext(ctx, getVacationTypeByID, id)
	var i VacationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemName,
		&i.ColorCode,
		&i.AffectsBalance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVacationTypeBySystemName = `-- name: GetVacationTypeBySystemName :one
SELECT
  id, name, system_name, color_code, affects_balance, is_active, sort_order, created_at, updated_at
FROM
  vacation_types
WHERE
  system_name = ?
`

func (q *Queries) GetVacationTypeBySystemName(ctx context.Context, systemName string) (VacationType, error) {
	row := q.db.QueryRowContext(ctx, getVacationTypeBySystemName, systemName)
	var i VacationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemName,
		&i.ColorCode,
		&i.AffectsBalance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVacationTypes = `-- name: GetVacationTypes :many
SELECT
  id, name, system_name, color_code, affects_balance, is_active, sort_order, created_at, updated_at
FROM
  vacation_types
ORDER BY
  sort_order,
  name
`

// ============================================
// vacation_types queries
// ============================================
func (q *Queries) GetVacationTypes(ctx context.Context) ([]VacationType, error) {
	rows, err := q.db.QueryContext(ctx, getVacationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacationType
	for rows.Next() {
		var i VacationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemName,
			&i.ColorCode,
			&i.AffectsBalance,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacationType = `-- name: UpdateVacationType :exec
UPDATE vacation_types
SET
  name = ?,
  system_name = ?,
  color_code = ?,
  affects_balance = ?,
  is_active = ?,
  sort_order = ?
WHERE
  id = ?
`

type UpdateVacationTypeParams struct {
	Name           string `json:"name"`
	SystemName     string `json:"systemName"`
	ColorCode      string `json:"colorCode"`
	AffectsBalance bool   `json:"affectsBalance"`
	IsActive       bool   `json:"isActive"`
	SortOrder      int32  `json:"sortOrder"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateVacationType(ctx context.Context, arg UpdateVacationTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateVacationType,
		arg.Name,
		arg.SystemName,
		arg.ColorCode,
		arg.AffectsBalance,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
