// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_standards.sql

package repo

import (
	"context"
	"database/sql"
)

const createWorkStandard = `-- name: CreateWorkStandard :exec
INSERT INTO work_standards (user_id, month, year, standard_hours, standard_days, gender)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWorkStandardParams struct {
	UserID        sql.NullString      `json:"userId"`
	Month         int32               `json:"month"`
	Year          int32               `json:"year"`
	StandardHours int32               `json:"standardHours"`
	StandardDays  int32               `json:"standardDays"`
	Gender        WorkStandardsGender `json:"gender"`
}

func (q *Queries) CreateWorkStandard(ctx context.Context, arg CreateWorkStandardParams) error {
	_, err := q.db.ExecContext(ctx, createWorkStandard,
		arg.UserID,
		arg.Month,
		arg.Year,
		arg.StandardHours,
		arg.StandardDays,
		arg.Gender,
	)
	return err
}

const deleteWorkStandard = `-- name: DeleteWorkStandard :exec
DELETE FROM work_standards WHERE id = ?
`

func (q *Queries) DeleteWorkStandard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkStandard, id)
	return err
}

const getWorkStandardsById = `-- name: GetWorkStandardsById :one

SELECT id, user_id, month, year, standard_hours, standard_days, gender, created_at, updated_at
FROM work_standards
WHERE id = ?
`

// ============================================
// work_standards queries
// ============================================
func (q *Queries) GetWorkStandardsById(ctx context.Context, id string) (WorkStandard, error) {
	row := q.db.QueryRowContext(ctx, getWorkStandardsById, id)
	var i WorkStandard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Year,
		&i.StandardHours,
		&i.StandardDays,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkStandardsByMonth = `-- name: GetWorkStandardsByMonth :many
SELECT id, user_id, month, year, standard_hours, standard_days, gender, created_at, updated_at
FROM work_standards
WHERE month = ? AND year = ?
ORDER BY gender, user_id
`

type GetWorkStandardsByMonthParams struct {
	Month int32 `json:"month"`
	Year  int32 `json:"year"`
}

func (q *Queries) GetWorkStandardsByMonth(ctx context.Context, arg GetWorkStandardsByMonthParams) ([]WorkStandard, error) {
	rows, err := q.db.QueryContext(ctx, getWorkStandardsByMonth, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkStandard
	for rows.Next() {
		var i WorkStandard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Year,
			&i.StandardHours,
			&i.StandardDays,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkStandardsByMonthAndGenderId = `-- name: GetWorkStandardsByMonthAndGenderId :one
SELECT id, user_id, month, year, standard_hours, standard_days, gender, created_at, updated_at
FROM work_standards
WHERE month = ? AND year = ? AND gender = ? AND (user_id IS NULL OR user_id = ?)
`

type GetWorkStandardsByMonthAndGenderIdParams struct {
	Month  int32               `json:"month"`
	Year   int32               `json:"year"`
	Gender WorkStandardsGender `json:"gender"`
	UserID sql.NullString      `json:"userId"`
}

func (q *Queries) GetWorkStandardsByMonthAndGenderId(ctx context.Context, arg GetWorkStandardsByMonthAndGenderIdParams) (WorkStandard, error) {
	row := q.db.QueryRowContext(ctx, getWorkStandardsByMonthAndGenderId,
		arg.Month,
		arg.Year,
		arg.Gender,
		arg.UserID,
	)
	var i WorkStandard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Year,
		&i.StandardHours,
		&i.StandardDays,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkStandardsByYear = `-- name: GetWorkStandardsByYear :many
SELECT id, user_id, month, year, standard_hours, standard_days, gender, created_at, updated_at
FROM work_standards
WHERE year = ?
ORDER BY month, gender, user_id
`

func (q *Queries) GetWorkStandardsByYear(ctx context.Context, year int32) ([]WorkStandard, error) {
	rows, err := q.db.QueryContext(ctx, getWorkStandardsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkStandard
	for rows.Next() {
		var i WorkStandard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.Year,
			&i.StandardHours,
			&i.StandardDays,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkStandard = `-- name: UpdateWorkStandard :exec
UPDATE work_standards
SET
    standard_hours = ?,
    standard_days = ?
WHERE id = ?
`

type UpdateWorkStandardParams struct {
	StandardHours int32  `json:"standardHours"`
	StandardDays  int32  `json:"standardDays"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateWorkStandard(ctx context.Context, arg UpdateWorkStandardParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkStandard, arg.StandardHours, arg.StandardDays, arg.ID)
	return err
}
